### ISSUE TITLE
UNIQUE constraint failing: assignee.id

### ISSUE THREAD

**Issue by rychipman** [magit/forge#10]
when running `F y` from the main magit popup
```
error in process filter: peculiar error: "UNIQUE constraint failed: assignee.id" [2 times]
```

**Comment by d1egoaz** [comment]
Tried in 2 different repos and I've got this same error

**Comment by schellj** [comment]
I'm getting a similar error with `' n`
```
peculiar error: "UNIQUE constraint failed: repository.id"
```

**Comment by tarsius** [comment]
If this happens for public repositories, then please mention those to make it easier for me to reproduce.  If it only happened in private repositories so far, then please try to find a public one in for which you can also reproduce this.

**Comment by schellj** [comment]
@tarsius able to repro with `git@github.com:gudtech/retailops-sdk.git`

**Comment by schellj** [comment]
Actually, can only repro the `' n` `UNIQUE constraint failed: repository.id` error, but not the `F y` `UNIQUE constraint failed: assignee.id` error with that repo.

**Comment by d1egoaz** [comment]
I could reproduce it with this public repo @tarsius 
https://github.com/Shopify/sarama

**Comment by m-cat** [comment]
Ran into this with https://github.com/maidsafe/safe_client_libs

**Comment by tarsius** [comment]
I was able to reproduce the `assignee.id` issue with these repositories.  The problem was that the data returned by the Github API contained duplicates, which Forge now filters out.

While I could not reproduce the `repository.id` issue and say in the commit message that the same problem wasn't reported for the `forks` field, I actually think now that this error is caused by duplication in the response data too (which just happen not to occur anymore for the given repository).

**Comment by ashiklom** [comment]
Sorry to bump this, but I'm hitting the (non-)unique `repository.id` issue with https://github.com/pecanproject/pecan. I am using the latest (2/22) version of `forge`, and am hitting the error even with a fresh clone. (If you are testing this, note that the repository is rather large -- ~400 MB. Sorry about that!).

**Comment by chase-dwelle** [comment]
Bumping as well since I found this happening on a public project: https://github.com/pyro-ppl/pyro.

It is still a large project (58 MB).

**Comment by scymtym** [comment]
I noticed today that the `UNIQUE constraint failed: repository.id` error happened for a repository that I had cloned into two different directories, let's call them `~/code/clone-a` and `~/code/clone-b`. More precisely, after successfully running `forge-pull` in `~/code/clone-a`, running `forge-pull` in `~/code/clone-b` resulted in the error.

And sure enough, `forge-reset-database` followed by `forge-pull` in `~/code/clone-b` made the second clone work. But after that, `forge-pull` in `~/code/clone-a` resulted in the error (as expected at this point).

So maybe the issue is (in some instances?) not with particular repositories and their contents, but instead cloning the same repository multiple times?

**Comment by gcentauri** [comment]
I ran into this issue today, and the `forge-reset-database` followed by `forge-pull` fixed the issue.

Unfortunately I can't report anything useful in terms of recreating the bug :\

One thing I did notice though... I believe this happened after two different PRs were opened from the same branch.  For example, branch `working` was pushed up to GitHub and a draft PR#1 was made.  I checked out that PR using `forge`.  PR#1 was then closed, and a new PR#2 was opened from the same branch `working` on GitHub.  Trying to pull notifications to checkout this updated PR#2 from the same branch is when I got the `UNIQUE constraint failing` issue.

**Comment by RadekMolenda** [comment]
I ran into the `UNIQUE constraint failed: repository.id` today. The issue I had was an origin remote url being wrong after we've changed the repo name in github.

**Comment by Azd325** [comment]
> I ran into this issue today, and the forge-reset-database followed by forge-pull fixed the issue.

Was the same for me.

**Comment by Fibrasek** [comment]
Running `forge-reset-database` did the job after manually editing `.git/config` from a repository renaming.

**Comment by tarsius** [comment]
I'll add a new issue about `UNIQUE constraint failed: repository.id`.
