### ISSUE TITLE
Allow creating pull requests without a forge-pull

### ISSUE THREAD

**Issue by aaronjensen** [magit/forge#102]
I often create PRs on repos that aren't mine. In those situations, I do not have any need to see a list of issues or PRs in magit, so requiring a `forge-pull` feels unnecessary (though maybe it currently is from a technical perspective).

**Comment by tarsius** [comment]
It's not absolutely necessary, but `forge-branch-pullreq` is already rather complicated and will need to be reworked to be easier to understand before an additional variant can be added to it.

**Comment by tarsius** [comment]
I have added experimental support for this.

To get started call the command `forge-set-buffer-repository`.  This is a bit weird because Forge should be able to detect the repository itself.  For now we do it like this because (1) this command additionally marks the repository "I will fetch individual topics individually" and (2) this is necessary to even support interacting with Forge repository without cloning the respective Git repository (see #121).

**Comment by tarsius** [comment]
test

**Comment by tarsius** [comment]
test

**Comment by tarsius** [comment]
test

**Comment by tarsius** [comment]
test

**Comment by tarsius** [comment]
Not sure why I though `forge-branch-pullreq` was relevant.  Anyway...

**Comment by tarsius** [comment]
Only pulling certain topics is supported now.

Use `forge-add-repostiory` instead of `forge-pull` to first add the repository.  You will be offered to only pull individual topics; choose that.  Later pull individual topics using `forge-pull-topic`.  If you us `forge-pull` instead, then you will be offered to upgrade the repository to "pull everything" mode.

You don't even need to clone the respective Git repository.  Add `forge-add-repository` you can insert any supported URL (or NAME or OWNER/NAME, see `magit-clone-name-alist`).

It's now also possible to navigate to a repository by pressing `RET` on the name of the repository in the list of notifications (as shown by `' l`).  Note that this will either show the Magit-Status buffer if the location of the local checkout is known.  (The location of that is automatically remembered when the status buffer is shown through other means, i.e. by navigating there explicitly.)

It's now also possible to list the known repositories using `' r`.  Here `N=t` means there is only an entry for that repository because fetching notifications made doing so necessary.  `S=t` means that topics are only fetched individually.
