### ISSUE TITLE
Customize display of PRs in magit-status (specifically, see author)

### ISSUE THREAD

**Issue by glasser** [magit/forge#116]
It would be great if you could customize the top-level line describing a PR in magit-status.

Specifically, I would want to add the PR's author to the line.

**Comment by xendk** [comment]
I'll vote for commit-status.

**Comment by tarsius** [comment]
> I'll vote for commit-status.

Different faces are used to indicate the status. Closed/merged topics are grayed out, assuming the theme did not mess with it.

**Comment by xendk** [comment]
I should have been clearer, I meant the commit (aka CI) status.

**Comment by tarsius** [comment]
Ah yes, I was wondering what you meant by *commit* status. See #92 for CI stuff.

**Comment by xendk** [comment]
Well, because that's what Github calls them: https://developer.github.com/v3/repos/statuses/ . It's a status attached to a commit. Annoyingly there's also deployments, reviews and check which I think all got their own APIs. All of which could be considered interesting information to get at a glance.

**Comment by tarsius** [comment]
You'll also have to update `magit`.
