### ISSUE TITLE
forge-topic.el overwrites bug-reference-fontify

### ISSUE THREAD

**Issue by jabranham** [magit/forge#135]
`bug-reference-fontify` is (re?)-defined in `forge-topic.el`, which overwrites the definition in Emacs's bug-reference.el.

**Comment by tarsius** [comment]
I noticed that when I did it. Does it cause any issues?

I have now marked the additions, see d803da1d817453684c644ef2822c7e29cee768e3.

**Comment by jabranham** [comment]
I just stumbled on it because I `M-.`'ed it while looking at something else in bug-reference.el and was surprised to find myself in forge-topic.el.

**Comment by zhenwenc** [comment]
After calling `forge-list-issues`, `bug-reference-prog-mode` will be enabled in all buffers (including non-[magit or forge] related buffers), which results in (transforming color code to bug reference hyperlinks):

![image](https://user-images.githubusercontent.com/5435340/55694968-9ce5f600-5a0a-11e9-8d32-ef0c75e74494.png)

Is it a bug somewhere? Thanks a lot in advance!

**Comment by tarsius** [comment]
I have noticed that before but was not bothered enough to do something about it. I would say that highlighting `#262626` is not a bug, but highlighting the first two characters of `#1e1e1e` is. Of course this could be extended to highlight no part of `"#262626"` either, trading false-positives for (likely much fewer) false-negatives.

The bug is in `bug-reference` and fixing it quickly on my side would probably involve redefining another function. And that's the only relation to what this issue is about.

**Comment by tarsius** [comment]
It's not ideal that the function is being redefined instead of merely being adviced, but since the necessary change is deep inside the function and does not affect other uses I think it is acceptable.
