### ISSUE TITLE
Compare to magithub

### ISSUE THREAD

**Issue by seagle0128** [magit/forge#15]
I was using [magithub](https://github.com/vermiculus/magithub). Now I found `forge` from `reddit` and am very interested in it. Can you please compare `forge` and `magithub` to access github via `magit`? It's a common question, I think. Thanks.

**Comment by fommil** [comment]
Personally I feel this is already addressed in https://emacsair.me/2018/12/19/forge-0.1/

**Comment by tarsius** [comment]
The announcement talks mostly about technical differences.  Well, it talks about "design decisions", but those also constitute differences to Magithub for the most part.

Functionality-wise there are some minor differences.  Most importantly Forge does not support displaying the CI status.  It also does not support adding personal notes to issues (mainly because if that feature existed, then having to discard the database due to breaking changes would be a much more serious issue than it is now (because currently all data can just be fetched again).

Then there are lots of tiny UI differences.  Magithub has a few additional faces that I haven't gotten around adding yet.  With Forge expanding a pull-request in the status buffer causes commits to be listed, Magithub shows some metadata instead.

I don't think compiling a list of minor UI differences would be all that useful.  Those differences will disappear over time and/or are rather insignificant.

The real difference is in how data is fetched and stored, as mentioned in the announcement.

**Comment by seagle0128** [comment]
Thanks for the explanations! It's helpful to me.

I believe `Forge` will be better and better. I decide to switch `magithub` to `forge`. Great work! Thank you!

**Comment by vermiculus** [comment]
I believe the same. As forge matures, I intend to rein back on what magithub provides; ultimately scaling back to the github-specific features. Consistency is King.
