### ISSUE TITLE
Problems with REST layer

### ISSUE THREAD

**Issue by Ninerian** [magit/forge#153]
I use Spacemacs with the restclient layer installed. When I make an request with the rest client, it seems to save the headers and then they are reused by forge. This results in an error, when the accept header is not json.

```
error in process filter: Failed to submit post: (error http 415 ((message . "Unsupported 'Accept' header: [#<Sinatra::Request::AcceptEntry:0x00007fc5cc2768e0 @entry=\"application/hal\", @type=\"application/hal\", @params={}, @q=1.0>]. Must accept 'application/json'.") (documentation_url . "https://developer.github.com/v3/media"))) 
```

## Steps to reproduce

1. add `rest-client` to `dotspacemacs-configuration-layers`
2. create a buffer with rest-client-mode
3. add a request and set `Accept: application/xxx`
4. execute the request
5. create a pull request and send it with `C-c C-c`
6. change header to `Accept: application/json`
7. send PR with `C-c C-c`

## System
- MacOS 10.14.4
- Emacs-mac GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.2.0, Carbon Version 158 AppKit 1671.2) of 2019-04-14
- SpaceMacs 0.200.13@26.2

**Comment by tarsius** [comment]
I don't see what that issue of `rest-client` has to do with this package (`forge`).

**Comment by vermiculus** [comment]
> When I make an request with the rest client, it seems to save the headers and then they are reused by forge.

@tarsius -- I think @Ninerian is saying there's some 'bleed over' from this rest-client package into the state used by forge. Is there a way to know if other REST services are affected? Then we could know if it's a problem in rest-client or a problem in ghub.

**Comment by Ninerian** [comment]
As it effects forge, it should be documented.

**Comment by Ninerian** [comment]
@vermiculus I'm relative new to emacs, so I don't know, how the Sinatra library comes into this. I couldn't find a trace in both libs.

**Comment by vermiculus** [comment]
Sinatra? Isn't that a ruby thing? (I wouldn't think sinatra has anything to do with this either.)

**Comment by tarsius** [comment]
I assume 2 through 4 are done using the `restclient` package and 5 through 7 are done using `forge`.  If you do 1 but skip 2-4 does 5-7 then succeed?

1. I don't use Spacemacs.
2. I assume you mean `restclient-mode`.
3. Please show the request.
4. Using the command `restclient-http-send-current`?
5. Are you doing that using Forge. Please mention how you do this. What keys do you press? Where? What is the command that you execute to create the request?
6. Forge does not allow you to change any headers so this is really confusing. Are you possibly not using Forge to create the pull-request?
7. What command is executed when you press those keys?

**Comment by tarsius** [comment]
Please post screenshots of what the buffer looks like when you press `C-c C-c` in 5 and 7.

**Comment by Ninerian** [comment]
I'll create a simple example to test it, and will provide the informations later.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by Ninerian** [comment]
Thanks for the ping, I forgot it.

**Comment by Ninerian** [comment]
Here is the repo with a simple test case
https://github.com/Ninerian/forge-test

**Comment by tarsius** [comment]
I can reproduce and found out why it happens.

`url` is quite weird and expects to be handed certain information in the form of dynamic bindings instead of using arguments. That weirdness leaks into non-trivial users of this library, as I have experienced when writing `ghub`, which is also quite weird.

The problem here is that `restclient` sets such a variable *globally* to pass the information instead of using only a dynamic binding. It *does* unset the old value, but only before itself makes another request. So my guess that the problem is related to `restclient` caching request headers was correct in a sense. However it does not intentionally cache things for its own purpose; it unintentionally caches headers for everyone making http requests *except* itself.

This was introduced in https://github.com/pashky/restclient.el/commit/5bbd1179ff5c86acb8546a4a897c94d28adadaa3. Maybe that was done because yet another package was illegally setting these variables but the commit message isn't clear about that.

I think that `restclient` should not set any of these variables globally. It may reset them to the default globally to deal with another package illegally setting them globally. It may also dynamically bind these variables. But it would probably be better to in each case figure out what other options are available to pass the respective information.

@pashky doesn't seem to be very active (see profile), but who knows, maybe they fix this quickly anyway. You (@Ninerian) should open a bug report in the `restclient` repository. You can copy this post there.

Meanwhile I will edit `ghub` to reset these variable to their default values before making a request. Of course that will break any legitimate uses of these variables but at least from the top of my head I cannot think of any.

**Comment by pashky** [comment]
@tarsius Dynamic binding is exactly what is happening here. There was no other binding types in 23.5 that I used at time of writing that code.

So this was (is?) the only way to pass values for headers in url.el as those are hilariously not part of actual function call. Perhaps 20 years ago headers were considered part of environment, but nowdays every sane code should set them all explicitly before doing HTTP call, I’d say. 

Feel free to fix it in any suitable way and raise a PR, I’ll merge it. I have neither time nor interest to touch it now, sorry.

**Comment by tarsius** [comment]
> Dynamic binding is exactly what is happening here.

My suggestion basically boils down to replacing this:

``` emacs-lisp
(setq url-mime-accept-string ...)
(url-retrieve ...)
```

with:

``` emacs-lisp
(let ((url-mime-accept-string ...))
  (url-retrieve ...))
```

The purpose of these variables is to allow you to pass information to the information to the function that makes the request.  But you are not supposed to set them permanently (globally), only temporarily (let-bound).  Obviously lexical bindings wouldn't work here, but that's not what I was trying to suggest and also not what `let` would do here because these are dynamic variables. 

> Perhaps 20
> years ago headers were considered part of environment, but nowdays
> every sane code should set them all explicitly before doing HTTP call,
> I’d say, but this api doesn’t make it clear. So just resetting those
> vars in any calling code is the only right thing to do.

Yes, the relevant headers should explicitly be set and that's what `ghub` does.  And I agree that the api (of `url`) doesn't make it clear how we are supposed to use it.

The problem in the case of `url-mime-accept-string` at least is that this is only one of the ways `url` lets you set that.

`ghub` sets `ACCEPT` header by let-binding `url-request-extra-headers` and `restclient` sets it by globally and permanently setting `url-mime-accept-string`.

`url-http-create-request` decides on the `ACCEPT` to be used using this

``` emacs-lisp
(concat
 ...
 "Accept: " (or url-mime-accept-string "*/*") "\r\n"
 ...)
```

So yes, setting `url-mime-accept-string` indeed appears to be the intended way to set the "ACCEPT" header and I will change `ghub` to do that.  However setting `url-mime-accept-string` permanently like your package does is still wrong as it needlessly affects other packages.

> Feel free to fix it in any suitable way and raise a PR, I’ll merge
> it. I have neither time nor interest to touch it now, sorry.

It's a rather trivial change... pr coming.

**Comment by tarsius** [comment]
Actually turns out `ghub` does not set `ACCEPT` explicitly. I intend to keep it that way because unless something else messes with it `ACCEPT: */*` is used which causes the default for the requested resource to be used. If we did it explicitly then we would have to determine that the appropriate value is in each case because it is not always the same. For the github graphql it does not even appear to be documented but I guess `application/json` would work. I am aware that some github resources that we use do not return json, but I don't remember what does are. Also in all the examples provided by github and gitlab this is not explicitly set, indicating that leaving this out is at least supported.

> Perhaps 20 years ago headers were considered part of environment, but nowdays every sane code should set them all explicitly before doing HTTP call,

Yeah well so my code is not sane.

**Comment by pashky** [comment]
Sure, just please test it, as I think it didn’t work with let when I tried, but memory of this is hazy now, it was long time ago. Really it should be no different to url-request-method.

**Comment by tarsius** [comment]
I don't actually use your package... @Ninerian please do the testing for us. Merely from reading the code I don't see how this could possibly not work.

**Comment by pashky** [comment]
> Yeah well so my code is not sane. Maybe sometime I will do this properly but I have already spend time fixing a bug in someone else's code and have exceeded the time I have initially allocated for this issue by far.

Oh come on. This is emacs, everything is global, zero isolation, been like this for decades. This is part of the charm, not the drama.

**Comment by tarsius** [comment]
Well I admit the combination of "Feel free to fix it in any suitable way and raise a PR, I’ll merge it. I have neither time nor interest to touch it now, sorry." and "nowdays every sane code should set them all explicitly before doing HTTP call" triggered me a bit. Though mostly I just felt I had to provide some justification for doing the "insane" thing.

> This is part of the charm, not the drama.

It's not a question of charm or drama. I like how there is zero separation for the most part--very empowering and all. It has its benefits and drawbacks. In this case we are dealing with a drawback. Your package has a bug that breaks my package. Because there is zero separation it is more important that we fix our own bugs because it affects innocent bystanders. So that's why the remark about "fixing someone else's bug" snuck in.

**Comment by tarsius** [comment]
So no hard feelings or anything. I hope @Ninerian can test my patch soon.

In any case I will have to keep the workaround that I have added to `ghub` anyway because not every user will update to a new version of `restclient` immediately.

**Comment by tarsius** [comment]
Actually I forgot to push this kludge, which I noticed when I started working on a feature that would *break* due to this kludge. (We need to bind one of these variables, so we can no longer force the default value to override a value that something else set permanently by mistake.)
