### ISSUE TITLE
UNIQUE constraint failed: label.id

### ISSUE THREAD

**Issue by chaoflow** [magit/forge#160]
I get the error on a fresh pull. It is caused if a project label and a group label with the same name exist. While I doubt that this setup makes sense it is possible to have it and magit-forge should deal with it gracefully. In Gitlab it is possible to choose one or the other, in magit-forge we have only textual input. We could prompt or simply chose one.

I suggest to pick the project label in case a project label and a group label exist with same name. There is a [flag](https://docs.gitlab.com/ee/api/labels.html#list-labels) distinguishing them.

**Comment by tarsius** [comment]
This is caused by:

```emacs-lisp
(cl-defmethod forge--update-labels ((repo forge-gitlab-repository) data)
  (oset repo labels
        (with-slots (id) repo
          (mapcar (lambda (row)
                    (let-alist row
                      ;; We should use the label's `id' instead of its
                      ;; `name' but a topic's `labels' field is a list
                      ;; of names instead of a list of ids or an alist.
                      ;; As a result of this we cannot recognize when
                      ;; a label is renamed and a topic continues to be
                      ;; tagged with the old label name until it itself
                      ;; is modified somehow.
                      (list (forge--object-id id .name)
                            .name
                            (downcase .color)
                            .description)))
                  data))))
```

I'll look into using the id anyway.

**Comment by tarsius** [comment]
Please check whether this "fixes" the issue, before I apply this kludge:

```diff
diff --git a/lisp/forge-gitlab.el b/lisp/forge-gitlab.el
index f684840..d34520a 100644
--- a/lisp/forge-gitlab.el
+++ b/lisp/forge-gitlab.el
@@ -404,6 +404,10 @@ (cl-defmethod forge--update-labels ((repo forge-gitlab-repository) data)
                             .name
                             (downcase .color)
                             .description)))
+                  ;; For now simply remove one of the duplicates.
+                  (cl-delete-duplicates .labels
+                                        :key (apply-partially #'alist-get 'name)
+                                        :test #'equal)
                   data))))
 
 ;;;; Notifications
```

The proper fix would be to first translate the label names that are listed for a topic to a list of label ids. But the problem is that in the label table only the id column is unique. Different repositories do have labels that have the same name. So we would have to add an additional column to the label table to store an additional reference to the repository. (There is already a reference to the repository because the id column encodes both the id of the repository as well as the label.)

For now I am just plan to drop one of the duplicates. This seems appropriate because Gitlab itself is not able to distinguish between two labels with the same name here.

**Comment by tarsius** [comment]
I don't see why it wouldn't, so I have applied it. Let me know if it turns out that it actually doesn't work.

Under that assumption I consider this a good enough kludge. And because I think Gitlab itself cannot deal with this properly itself I consider it fixed even. Adding the `scheme` label, because once I make changes to the table schemata anyway, I might add the additional column.

**Comment by chaoflow** [comment]
@tarsius Thank you very much for the fix! Meanwhile, I'm not anymore able to reproduce a GitLab project with duplicate labels and therefore can't test.

**Comment by chaoflow** [comment]
@tarsius Pulling https://gitlab.com/ApexAI/grge with forge-20190621.1326 I get the following error:
```
Pulling ApexAI/grge...
Pulling ApexAI/grge issues...done
Pulling ApexAI/grge pullreqs...done
Pulling ApexAI/grge...done
Storing ApexAI/grge...
error in process filter: apply: Symbol’s value as variable is void: \.labels
error in process filter: Symbol’s value as variable is void: \.labels
```

The error persists also after resetting the database.

**Comment by tarsius** [comment]
That was a weird bug. No idea how I ended up writing that. Pushed a fix.

**Comment by chaoflow** [comment]
@tarsius I can confirm that it works now with 20190622.1358. Thank you very much!
