### ISSUE TITLE
notification pulls should be asynchronous

### ISSUE THREAD

**Issue by Boruch-Baum** [magit/forge#166]
Notification pulling can take a long time, so it would be nice to have
it done in the background so that users can doing something else while
the operation is being performed.

This is also desirable because sometimes when asking forge to perform
some other operation, it first performs another notification-pull. For
example, when adding a comment to an issue, one first needs to wait.

**Comment by Boruch-Baum** [comment]
Also, after performing operations, such as creating this issue, another notification pull was performed...

**Comment by tarsius** [comment]
> Notification pulling can take a long time, so it would be nice to have
> it done in the background so that users can doing something else while
> the operation is being performed.

The fetching is already being done asynchronously. Only the parsing and storing is done synchronously but those are quite quick. I don't plan to make it more asynchronous; at least not any time soon.

> This is also desirable because sometimes when asking forge to perform
> some other operation, it first performs another notification-pull.

A lot of work is still necessary to improve the experience better concerning notifications and un-/read topics. The underlying cause here is that the information provided by Github is less than helpful. For example its a case where the use of graphql would be particularly helpful, but its also one that is only available using REST. Also if you yourself comment using the web interface, then the api considers that reply something that you yourself have not read yet.

Point being, there's a lot to be improved here and what you are reporting is merely a symptom. Which is why I am closing this.

> For example, when adding a comment to an issue, one first needs to wait.

I don't think that's true. You *do* have to wait if you want your reply to appear below the others, but since you just wrote it that might not actually be necessary. Other things you can do immediately though.

**Comment by tarsius** [comment]
You might want to set `forge-pull-notifications` to `nil` and instead fetch notifications explicitly. I am considering making that the default one more but haven't decided yet. Might also dive in instead and make larger changes. Or not trying to concentrate on the low-hanging fruit right now.
