### ISSUE TITLE
Delete post does not work - and is called "delete comment"

### ISSUE THREAD

**Issue by snogge** [magit/forge#195]
Comments on issues and PRs are calles "posts" everywhere(?) except when deleting them, then they are called "comments":  See forge.org section "Editing Topics and Posts".  The command is also called `forge-delete-comment`.  The `forge-delete-comment` command uses `forge-comment-at-point` instead of `forge-post-at-point`. `forge-delete-comment` is the only user of `forge-comment-at-point`, which is a good thing as that function is broken. It returns `t` instead of the `forge-post` object at point.

I think I got all of that right :)

**Comment by tarsius** [comment]
A comment that will be deleted.

**Comment by tarsius** [comment]
> Delete post does not work

That is indeed a bug.  I have fixed it with 5b1477976cea6c5134024e9fff82faef6cd2874f.

> and is called "delete comment"

That is intentional because it can only delete comments; not actually every post.

Every comment is a post, but
not every post is a comment.

When someone opens a new issue or pull-request, then the initial description that they write is treated as a "post" by `forge`. When someone comments, then that text is also a post. We call it a "comment" to distinguish it from the other kind of post.

Only this second type of post can be deleted by this command. In a rare case someone might want to delete the initial issue/pr description, but (1) I think that is usually not an appropriate thing to do, and (2) it has to be implemented differently because the forges we deal with also handle it differently.

Iff we actually do that, then we can rename the command. But since I think it is usually wrong to delete the intial issue/pr description, I am in no hurry to do that. If someone really wants to delete the initial description, then they can **edit** the initial description in order to use the empty string as the description.
