### ISSUE TITLE
Order pull request targets

### ISSUE THREAD

**Issue by codygman** [magit/forge#212]
I want this to put `origin/master` first since 90% of the time my workflow calls for origin/master. I'm betting others might be in a similar position so it might be useful to have an option for this.

**Comment by tarsius** [comment]
I assume "this" means `forge-create-pullreq`.

I also assume that for you and given a branch named `my-new-feature` it instead suggests `my-fork/my-new-feature`. If so, then that is because you are not following the advice at [The Two Remotes](https://magit.vc/manual/magit/The-Two-Remotes.html).

This prompt defaults to the upstream branch, which should usually be `origin/master`. In other words if things are configured "properly" it should already do what you suggest.
