### ISSUE TITLE
Failed to create PR on github

### ISSUE THREAD

**Issue by antoine-levitt** [magit/forge#226]
I get
```
error in process filter: Failed to submit post: (error http 404 ((message . "Not Found") (documentation_url . "https://developer.github.com/v3/pulls/#create-a-pull-request"))) [2 times]```
when submitting a PR to github

**Comment by tarsius** [comment]
I'll need more information than that.
Do other requests in that repository succeed?
Was the repository renamed on Github?
What is the url?
...

**Comment by antoine-levitt** [comment]
I think 

> Was the repository renamed on Github?

is the correct guess. The repo was moved between two different github accounts, and the git URL pointed to the previous one (which is OK for all my git operations, and things like commenting on an issue with forge). I was just surprised because I thought the 404 refered to the documentation URL. I'll try next time I make a PR to that repo.

**Comment by antoine-levitt** [comment]
Yup, that was it, I changed the URL to the new one and it works now. Is it possible for forge to detect that and suggest the user to fix their URL?

**Comment by tarsius** [comment]
The api isn't being helpful here. It could provide more information in the error message. Or it could even just redirect like the web interface does. Sadly it does't do either of those things.

We *could* try to retrieve the respective web page whenever an api request fails with a 404, but that seems like overkill and delays showing the error.

**Comment by robohack** [comment]
I would like to have this issue reconsidered, unless of course it is decided it really is just a Github bug _and_ that some progress can be made in fixing it.

I think this problem is one that will only increase in frequency as churn happens on Github over time.

I encountered it again yesterday with a rename from conserver/conserver to bstansell/conserver.

All normal git (and magit) things continued to work fine with my clone from the first URL, and forge was even able to fetch all the issues and PRs from there as well.

So, since the `forge-pull` had worked with the aliased URL, the result of failing to post a new PR was doubly confusing.

Posting  a PR failed, as originally reported here, with the same highly cryptic error message:

	error in process filter: Failed to submit post: (error http 404 ((message . "Not Found") (documentation_url . "https://docs.github.com/rest/pulls/pulls#create-a-pull-request") (status . "404")))

Then when I guessed at the problem (long before seeing this issue report), I changed the URL in my clone's `.git/config` only to be even more confused as suddenly the previously visible issues and PRs disappeared!  None of the issues or PRs were visible any more in the magit status buffer any longer, and of course posting a PR also still didn't work.

The the fix was to `forge-remove-repository`, fix the URL in the git config, and then `forge-pull` again.

I'm guessing the problem is that just some part of the Github API doesn't follow the aliased URL properly.  I don't know enough about using the API, or how `forge-pull` works to know if the problem is this simple or not though.  Really if `forge-pull` works I would think other forge things should work as well.

So this might arguably be a Github bug, but chasing down the cause of the problem in magit/forge was quite an adventure and I would hope for some better error report from forge, if at all possible.

For the record I have:

Magit 3.3.0, Git 2.35.1, Emacs 26.3, berkeley-unix
