### ISSUE TITLE
Submit PR's without forge-pull

### ISSUE THREAD

**Issue by rgrinberg** [magit/forge#230]
forge-pull can be quite slow and also unnecessary in cases where a repo is cloned just to submit a single PR. It would be nice if it worked without pulling, even if some functionality was reduced.

**Comment by tarsius** [comment]
That's already possible, see #102.

**Comment by rgrinberg** [comment]
Looks good, but to be honest it’s a lot to remember for day to day use. I think forge should just offer to create the repository and pull the required topic.

**Comment by tarsius** [comment]
> Looks good, but to be honest it’s a lot to remember for day to day use.

Not really. Most of the information in #102 are details you don't necessarily have to know about. All you have to know is this: Instead of using the "pull everything" command, use the "add repository" command and then answer "do not pull everything".

> I think forge should just offer to create the repository and pull the required topic.

I have essentially done that now, except that instead of doing it without user intervention it tells you to do `Use M-x forge-add-repository before trying again` and you then have to do that. I also added a FAQ entry and other documentation.
