### ISSUE TITLE
Error when pulling from a GitLab repository with merge requests disabled

### ISSUE THREAD

**Issue by desiderius** [magit/forge#235]
When invoking the `forge-pull` command on a GitLab repository with merge requests disabled the following error is returned:

```
error in process filter: ghub--signal-error: HTTP Error: 403, "Forbidden", "/api/v4/projects/<removed>/merge_requests?per_page=100&order_by=updated_at&updated_after=", ((message . "403 Forbidden"))
```
![merge-requests-disabled](https://user-images.githubusercontent.com/1311761/71821208-cca55580-3091-11ea-9180-21b80539d488.png)

```
magit     20200102.2204
forge     20200102.2204
ghub      20200102.2204
```

**Comment by tarsius** [comment]
I had a look and it shouldn't be to hard to prevent this using either the deprecated `merge_request_enabled` or better `merge_request_access_level`. Unfortunately the documentation at https://docs.gitlab.com/ee/api/projects.html#create-project-for-user is not sufficient so I will have to experiment a bit.

In particular I do not know if `merge_request_enabled=private` means:
1. It's enabled for you but not for others.
2. It's enabled for others but not for you.
3. It's enabled for a subset of people and some other variable (which?) says whether that includes you or not.

But so far I could not experiment because I could not find the setting page from your screenshot. Is this only available when using the proprietary version of gitlab? If it is also available in the free version, then please show me how to navigate to that page.

**Comment by tarsius** [comment]
Please also setup a repository that enables merge-requests for you but without giving me access.

**Comment by tarsius** [comment]
Going with the deprecated values for now. When you help me with the mentioned things, then I can improve this.
