### ISSUE TITLE
forge--split-url-path with private gitlab instance and subproject

### ISSUE THREAD

**Issue by green7ea** [magit/forge#236]
When using forge 0.1.0 with a custom forge-alist:

```
("gitlab.company.local" "gitlab.company.local/api/v4")
```

and a project repository:

```
git@gitlab.company.local:dev-group/project.git
```

doing a forge-pull gives the error:

```
No applicable method: forge--split-url-path, nil, "dev-group/project"
```

Is this a misconfiguration or is split-url having a hard time parsing this url structure?

**Comment by tarsius** [comment]
> When using forge 0.1.0

Please use the development version instead. Most likely it has been fixed there a long time ago. I'll create a new release within the next month or so. I recommend you discard your existing forge db and start over after updating to the development version.

**Comment by rassie** [comment]
For anyone finding this issue after banging your head on the wall for a couple of hours: `forge-alist` is not a list of URLs as it may seem. It requires three parameters for each entry. 

From code documentation:
```
Each entry has the form (GITHOST APIHOST ID CLASS).
GITHOST is matched against the host part of Git remote urls
  using `forge--url-regexp' to identify the forge.
APIHOST is the api endpoint of the forge's api.
ID is used to identify the forge in the local database.
CLASS is the class to be used for repository from the forge.
``` 
So in OP's problem, the line should read `("gitlab.company.local" "gitlab.company.local/api/v4" "gitlab.company.local")` instead of `("gitlab.company.local" "gitlab.company.local/api/v4")` (note the third element). Otherwise the comment about obsolete version stands, so the correct current version should look like `("gitlab.company.local" "gitlab.company.local/api/v4" "gitlab.company.local" forge-gitlab-repository)`.
