### ISSUE TITLE
Status Update Gitea

### ISSUE THREAD

**Issue by nils-schween** [magit/forge#254]
Hi everyone,

and thanks for the great work which is done here.  Maybe the issue tracker is not the right place for this question, but I did not find a good place where to ask it. What's the current status of the gitea forge implementation?
> This is the next forge whose API will to be supported. 

I tried to set up forge for gitea, to see what exactly is meant by partially supported. In the manual I found the following 

> When a forge is only partially supported, then that means that only the functionality that does not require the API is implemented, or in other words, that the forge is only supported as a semi-forge. 

I do not know if for example filing an issue needs the API. Does anyone have an example setup to test what's supported and what's not? I was for example wondering what to put in .authinfo file and what to add to forge-alist.
I tried the following 
`machine mygitea-server.org/api/v1 login myuser^forge password gitea-token`
`(add-to-list 'forge-alist '("mygitea-server.org" "mygitea-server.org/api/v1" forge-gitlab-repository))`

Thanks.
If you think that's the wrong place for my question. Never mind and close the issue.

**Comment by tarsius** [comment]
The API token is used to access the API, so since we don't support the API yet, making it available to `ghub` doesn't do anything.

Doing things to issues requires the API.

Commands that are probably supported are forge-browse-dwim, forge-browse-commit, forge-copy-url-at-point-as-kill, forge-browse-branch, forge-browse-remote, forge-visit-repository and forge-fork. But that's about it.

**Comment by tarsius** [comment]
I have added [a faq entry](https://github.com/magit/forge/wiki/FAQ#do-you-plan-to-addextend-support-forge-x) about the forges I plan or don't plan to support. Because I do not plan to implement support for this particular forge I am closing this issue. That doesn't mean that you cannot comment here or shouldn't discourage you from contributing support for favorite forge yourself.

**Comment by nils-schween** [comment]
Thank you!

**Comment by oatmealm** [comment]
You should proably focus on forgejo .... https://forgejo.org/faq/

**Comment by tarsius** [comment]
I am interested in using Codeberg (and I believe Gitea still hasn't managed to make their own instance available), so yes, I will likely focus on that.

But from the FAQ I gather that supporting one would likely mean the other is automatically supported too, so it shouldn't matter much which I concentrate on (once I actually get around to that in the first place).

**Comment by mstenek** [comment]
Perhaps this helps:
- [forgejo API](https://codeberg.org/api/swagger)
- [gitea API](https://try.gitea.io/api/swagger)

**Comment by zzantares** [comment]
@tarsius would you consider to re-open this? while `forge-alist` has an entry for `codeberg.org` trying to add a repository results in:

```
forge--ghub-type-symbol: No clause matching ‘forge-forgejo-repository’
```

**Comment by tarsius** [comment]
I now use "idea" discussions for new features and have opened #771 to track this.
