### ISSUE TITLE
Add Phabricator support

### ISSUE THREAD

**Issue by hexmode** [magit/forge#258]
Phabricator supports issue (task) reporting and can host git repositories.

**Comment by hexmode** [comment]
Is there documentation or (better!) a tutorial for how to add forge support?

**Comment by tarsius** [comment]
No but I tried to write the forge-specific bits in a somewhat self-explanatory way. Generic functions are used and you can look at the methods for Gitlab to learn what you have to do and more or less how to do it. (You can also look at the Github implementation, but that uses GraphQL, which I suspect no other forge does at this point.)

**Comment by tarsius** [comment]
I have added [a faq entry](https://github.com/magit/forge/wiki/FAQ#do-you-plan-to-addextend-support-forge-x) about the forges I plan or don't plan to support. Because I do not plan to implement support for this particular forge I am closing this issue. That doesn't mean that you cannot comment here or shouldn't discourage you from contributing support for favorite forge yourself.
