### ISSUE TITLE
Notify user if trying to create PR without pushing first?

### ISSUE THREAD

**Issue by unhammer** [magit/forge#303]
When you're on a branch that hasn't been pushed and you try to create a PR, it'd be nice to get a message about that, instead of just a list of completions without your branch in it :-) 

(With forge-20201002.1420 from melpa, I made a new branch and committed some changes, then did `@cp` to create a pull request, and I couldn't find my branch in the list. I got confused about whether I had to select the feature branch or master first or last. But the problem was that I hadn't pushed first, so my branch didn't show up in the list. I've done this before and forgotten what the problem was. A warning would improve quality of life.)

**Comment by tarsius** [comment]
I think it is fine as-as. If it turns out that there are others who have the same issue and care enough to come here and talk about it, then I am of course willing to reconsider.

Adding such a warning would be annoying and potentially confusing for users who create pull-requests while having an unrelated branch checked out.

> I've done this before and forgotten what the problem was.

Probably won't happen again now. :grinning:
