### ISSUE TITLE
Support adding bug reference tokens and URLs per forge/forge-type

### ISSUE THREAD

**Issue by Thaodan** [magit/forge#319]
Some projects use other bugtrackers in addition to Gitlab/Github issues.
It would great if there was the possibility to be able to configure additional 
tokens that match a bugtracker URL e.g  `EXAMPLE#1` -> `bz.example.com/show_bug.cgi?id=1`

**Comment by tarsius** [comment]
We have had a few interactions today and every single time I was confused about what you are actually trying to tell me. Please make a bit more of an effort to communicate clearly.

Anyway. Forge uses `bug-reference` to linkify the issue markers. It actually has to override some code of that package to do so. This is not a satisfying situation. I am under the impression that `bug-reference` is not really up to the task and will have to be replaced eventually. Doing that will be a major effort and ideally would involve getting the result into Emacs, which would be even more of an effort.

Eventually I am probably going to undertake that task. Or not.

Meanwhile you could probably get `bug-reference` to support links to multiple pages/services/forges within the same repository using some prefix as identifier as you have suggested. But this has little to do with Forge and could be implemented just by extending/patching `bug-reference.el` without involving Forge at all.

I am closing this because there is nothing for me to do here in the short- to midterm.

**Comment by Thaodan** [comment]
Am Mittwoch, 9. Dezember 2020, 02:14:01 EET schrieb Jonas Bernoulli:
> We have had a few interactions today and every single time I was confused
> about what you are actually trying to tell me. Please make a bit more of an
> effort to communicate clearly.
Sorry that was not my intend.
> Anyway. Forge uses `bug-reference` to linkify the issue markers. It actually
> has to override some code of that package to do so. This is not a
> satisfying situation. I am under the impression that `bug-reference` is not
> really up to the task and will have to be replaced eventually. Doing that
> will be a major effort and ideally would involve getting the result into
> Emacs, which would be even more of an effort.
I was under the impression that forgot overrides these bug-reference markers.


> Eventually I am probably going to undertake that task. Or not.
> 
> Meanwhile you could probably get `bug-reference` to support links to
> multiple pages/services/forges within the same repository using some prefix
> as identifier as you have suggested. But this has little to do with Forge
> and could be implemented just by extending/patching `bug-reference.el`
> without involving Forge at all.
My idea was either adding a gitconfig variable to add more tokens and match 
these to  that  token I thought that was clear by my explanation.
From what I've looked `bug-reference` is definitely a bit limited.
