### ISSUE TITLE
Commits not showing in PR

### ISSUE THREAD

**Issue by xzebra** [magit/forge#320]
I'm creating this issue as the owner of the original comment hasn't done it in a while. I'm using Doom Emacs too, so it could be a doom problem, not forge.

I've followed this steps in order to configure forge:
* add `(magit +forge)` to `init.el`
* generate a Github token with: read:org, repo, user 
* edit `.authinfo.gpg` to use that token
* `M-x forge-pull`

The pull requests and issues are listed, even the comments. But the commits header seems to be empty when I enter `forge-topic-mode`.

_Originally posted by @nicu-chiciuc in https://github.com/magit/forge/issues/134#issuecomment-695195205_

**Comment by tarsius** [comment]
Just to make sure: did you put the cursor on the "Commits" line and press <kbd>TAB</kbd>?

**Comment by xzebra** [comment]
Yes I did. But it shows only the header _Commits_ with no commits, followed by the comments.

I'm not posting a picture as the referenced comment already has one. But if you need any info I will be glad to help.

**Comment by Manu-Tran** [comment]
I am reporting the same issue on my side, with exactly the same setup ! I also unsuccessfully tried to unroll the Commits line as you suggested. Happy to help if you need more informations.

**Comment by tarsius** [comment]
Doh.

The problem likely is that the respective ref does not actually exist locally. `forge--insert-pullreq-commits` tries to insert the log for a range such as `origin/master..refs/pullreqs/266`. Use a debug statement such as `(message "range: %s" (forge--pullreq-range pullreq))`, which it is in your case. Then check if the pr ref actually exists.

If not, then check the local config file `.git/config` and look for something like:

```
[remote "origin"]
	url = git@github.com:magit/forge.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	fetch = +refs/pull/*/head:refs/pullreqs/*
```

If the `fetch = +refs/pull/*/head:refs/pullreqs/*` is missing that's why the ref is missing. And the refspec is probably missing because you chose to not add it when you configured this repository for forge. To add thre refspec use `M-x forge-add-pullreq-refspec`.

**Comment by JasonMFry** [comment]
> If the `fetch = +refs/pull/*/head:refs/pullreqs/*` is missing that's why the ref is missing. And the refspec is probably missing because you chose to not add it when you configured this repository for forge. To add the refspec use `M-x forge-add-pullreq-refspec`.

This was the solution for me, thanks!
