### ISSUE TITLE
github 422 when creating pull request from fork

### ISSUE THREAD

**Issue by MartinNowak** [magit/forge#33]
```
error in process filter: Failed to submit post: (error http 422 ((message . "Validation Failed") (errors ((resource . "PullRequest") (field . "head") (code . "invalid"))) (documentation_url . "https://developer.github.com/v3/pulls/#create-a-pull-request"))) [2 times]
```
Using `origin/only_count_active_servers` as source and `upstream/master` as target with the following remote configs.

```bash
$ git remote -v
origin	git://github.com/MartinNowak/dlang-bot.git (fetch)
origin	git@github.com:MartinNowak/dlang-bot.git (push)
upstream	git://github.com/dlang/dlang-bot.git (fetch)
upstream	git@github.com:dlang/dlang-bot.git (push)
```

Also tried both, explicity setting `upstream/master` as target and configuring `branch.remote` to `upstream/master`. The latter works to fill-in `upstream/master` as default target, but doesn't resolve the problem.

**Comment by iocanel** [comment]
@tarsius:  Thanks a lot for all the great stuff you put out there!

I am having the same issue with the current master. Shall I create a new issue, or we can get this re-opened ?

**Additional info**
I keep all my forks in a dedicated org of mine and I create my pull requests from there.
My username is `iocanel` and my forks are hosted under `ioforks`.

When I create pull requests, I do seem to get the exact same error! 

It seems to me that in `forge--submit-create-pullreq` the `(oref head-repo owner)` returns my github username (`iocanel`) instead of the org from which the pull request gets created (`ioforks`).

**Comment by tarsius** [comment]
My guess is that you select a remote branch as source (`feature`) instead of a remote branch (`ioforks/feature`) *and* that the push-remote is set to `iocanel`. `forge-create-pullreq--read-args` then translates `feature` to `iocanel/feature`. Make sure you provide the remote branches to avoid this issues.

If its not that, then add debug statements to inspect the values of `forge--buffer-head-branch` and `forge--buffer-base-branch`.
