### ISSUE TITLE
No way to configure upstream ("merge") when checking out a PR

### ISSUE THREAD

**Issue by Stebalien** [magit/forge#359]
When checking out a PR, upstream (`branch.<branch-name>.merge`) is always set to either "master" or `<upstream>/master`, depending on `magit-branch-prefer-remote-upstream`. I'd like to just leave it unset so `git pull` pulls from the current branch's remote but there doesn't appear to be a way to do this:

https://github.com/magit/forge/blob/aa5891178aa67d61ec17069375c07ca989f5741e/lisp/forge-commands.el#L673-L677

Yes, I know I can just do this through the magit UI by fetching from the "push" remote, but:

1. Muscle memory (`git pull` to fetch the latest changes on a PR).
2. Lots of scripts assume that `git pull` will pull from the branches upstream, not rebase on master.

Is there any way this could be made configurable?

**Comment by tarsius** [comment]
> Is there any way this could be made configurable?

No, there probably is code in Forge that depends on this being configured.

And even if that weren't the case it would still be undesirable to not configure the upstream because Magit certainly becomes more useful if this is configured correctly. If the upstream is not set, then Magit cannot show the list of commits that are on the pull-request but not on the branch into which it is supposed to be merged. Obviously that list is extremely useful.

I understand your concern isn't about concepts but muscle memory but this might still be helpful: https://magit.vc/manual/magit/The-Two-Remotes.html.

**Comment by tarsius** [comment]
Ps: There are many variables that affect `git pull`. It might be possible to get it to do what you want even when the upstream is configured. Otherwise you could define an alias that does what you want, e.g `git pu`.

**Comment by Stebalien** [comment]
A _normal_ `magit-branch-checkout` against a remote branch _doesn't_ do this (at least with my magit config). Are you sure this command shouldn't be using `magit-branch-maybe-adjust-upstream`?

**Comment by tarsius** [comment]
Yes I am sure. This are very different situations.

(I am on vacation.)
