### ISSUE TITLE
Document single-sign-on on manual

### ISSUE THREAD

**Issue by Andre0991** [magit/forge#361]
Hello.

I have an `authinfo` file that used to work with `forge` last year. Today, I tried to use forge again and I got this error when trying to add any repo:

```
ghub-repository-id: Repository "<my-company>/<my-repo>" does not exist on "api.github.com".
Maybe it was renamed and you have to update "remote.<remote>.url"?
```

I read `forge`s manual again and everything looked fine.
Finally, I found that I needed to go to https://github.com/settings/tokens and click on "Enable SSO", as shown in the image below (another token with other permissions just as an example).

![image](https://user-images.githubusercontent.com/7083061/118413695-01a6bc80-b677-11eb-9500-ffb1a6eb704c.png)

Now, if one is creating a new token, I suppose this issue is less likely to happen, but still, I'm just wondering if it would make sense to mention SSO in the instructions for creating a new token.

**Comment by tarsius** [comment]
Thanks for letting me know about the "new token formats"; I wasn't aware.

If I understand you correctly, then you did *not* regenerate your tokens before you started getting this error, and you assume that because you had not done things stopped working. I don't think you assumption is correct; I have not updated my tokens and yet forge/ghub continued to work. I guess we'll never know what really happened.

When a user "regenerates" a token (as in "replaces it with another"), then this text is displayed next to the "Regenerate token" button:

> If you’ve lost or forgotten this token, you can regenerate it, but be aware that any scripts or applications using this token will need to be updated.

So I don't think anything should be added to the manual.

**Comment by Andsbf** [comment]
> **[Andre0991](/Andre0991) ** c

Thanks for sharing, saved me a few hours FOR SURE!
