### ISSUE TITLE
Notification Refresh and Clearing

### ISSUE THREAD

**Issue by fosskers** [magit/forge#367]
Hi there, I love Magit (thank you!) and recently started using Forge. I'm hoping
that Forge can free me from having to visit Github myself and from relying on
`gh` for repo cloning and PR opening. For the latter, this already seems doable!
And to put my money where my mouth is, I'm opening this issue from within Forge,
cloned via Magit :)

The last hurdle seems to be Notifications. Myself and others have noted some
strange behaviours and are wondering if our assumptions or usage are incorrect.

For context, I'm pinned to Forge `0.2` and Magit `3.0`. I use evil, with which
the Forge leader key seems to be `@` (see below).

### Notification Pulls and Display

`f Y` pulls a lot of notifications, mostly stale ones for issues/PRs that I've
long since read or marked closed. Most of them don't appear in the Inbox area of
my Notifications UI on Github itself, although they would have at some point.
For reference, I current have 6 "unresolved" (yet read) notifications in my
Github Inbox, but have 62 notifications in my Forge Notifications buffer.

Calling `f Y` once again seems to pull the entire batch again, as opposed to
fetching a smaller diff, etc. But it's hard to know for sure due to the clearing
issues described below.

Note also that the special notifications buffer (`@ l n`) seems unaffected by settings like:

``` emacs-lisp
(setq forge-topic-list-limit '(60 . -1))
```

Although this does have a nice affect in the Status Buffer.

### Notification Clearing

Despite what https://github.com/magit/forge/issues/111 advertises, I can't seem
to make any notifications disappear, either from the normal Magit Status Buffer
or from the special notification buffer summoned by `@ l n`. Visiting a topic
(by pressing Enter) this way doesn't clear the notification when I revisit the
notifications buffer.

As with many other things in Magit, I expected to be able to `x` over any
notification and have it disappear. I was surprised when it complained to me that
"there is nothing to be removed at point". I also assumed there would be a
public command like `forge-clear-notifications`, but there doesn't seem to be
one. Is there a way to clear notifications that I haven't discovered?

As a last minor point: if we don't have a local clone of a particular repo
listed in our notifications buffer, there is no way to visit its Topics, even if
we have told Forge about it via `forge-add-repository`. Pressing enter on an
"orphan" notification like this gives the following in the modeline:

> No applicable method: forge-visit, nil

And without a general way to clear notifications, these orphans remain stuck, ghost-like in that buffer forever :ghost: 

There is a lot here to chew on, so please let me know if you'd like this filed
as separate issues, or if you like actual backtraces, etc. Nothing actually
throws an exception, as far as I can tell.

Thank you!

**Comment by daviwil** [comment]
I agree, I love Forge and the notifications UI might be the most useful part for me to remove the need to check https://github.com/notifications every day.  If we could make the Forge notifications list reflect what's on the GH notifications page more accurately, that would be perfect.  Maybe it requires using the GraphQL API?

**Comment by fosskers** [comment]
As far as I'm aware the Github code specifically does already use the GraphQL API.

**Comment by tarsius** [comment]
> Maybe it requires using the GraphQL API?

I would go as far as to say that this could serve as a good example when explaining why it make sense to implement some APIs using GraphQL. Strangely enough it is also one of the few areas where Github does *not* support GraphQL and one has to fall back to the older REST API. [At least last I checked.]

**Comment by daviwil** [comment]
Oh yeah, I forgot about that...  I once tried to snoop on the requests going from the https://github.com/notifications page to see what API requests they're making and it seems like they're actually reloading HTML fragments instead of making API requests.  Sneaky...

I don't see notifications in the GraphQL API either, so I can understand the challenge of implementing this properly!

**Comment by fosskers** [comment]
Ah, pardon me then, I was mistaken! In that case I'll send karma waves in the direction of the nearest Github office...

Well, in the meantime, having `x` (or similar) bound to a function that changes a topic's status to `read` in the DB would be a big step forward. Is something like that PRable, or would it be trivial for somebody already in-the-know to whip out?

**Comment by anticomputer** [comment]
@fosskers I ran into the same issue, as an interim fix to not be lagged out when juggling (a lot of) GitHub notifications via magit/forge I made a little notification-veneer on top of forge that adds incremental notification juggling (i.e. you don't have to refetch everything just to get your new notifications), you can find it at https://github.com/anticomputer/gh-notify

it integrates tightly with existing magit/forge functionality and I use it pretty heavily every day juggling large amounts of notifications

**Comment by tarsius** [comment]
I've just pushed a big change which includes improved support for notifications.

The reason notification support in Forge was so poor, is that Github's notification API is abysmal.  It is so incredibly bad that I assumed they would surely fix it within a few months or so, which is why I didn't try harder to work around the defects when I first released Forge.  It's now five years later and hasn't changed a bit, so I finally started to work around the "limitations" in their API.

A notification is in one of **three states** "unread", "pending" or "done" and the API represents this using a **boolean**.  (This is the worst defect, but it's also just the tip of the iceberg.)

It is impossible to properly synchronize the state between Github and a client.

We can however set the local state based on the obfuscated state the API hands us.  You will need to customize `forge-notifications-github-kludge` to configure how to interpreted the insufficient data the API provides.  I recommend using the `pending-again` approach, but your mileage may vary (and also change over time, as you become more accustomed to dealing with notifications using Forge).  You will probably be surprised by the behavior a few times, but with some practice it should become usable enough to do it all from Forge.

Synchronizing in the other direction also is not possible, at least not completely.

(The API supports putting a notification in the "pending" state but not in one of the other two states.  Currently Forge doesn't use that "feature" because doing so [might have the opposite of the desired effect](03145ea10b6b49f5ab9781155606be4b7bfc2fda), and I am not sure it is worth the effort, given that just 1/3 of the states are supported.

This means that once in a while you will have to go through the list on github.com and mark some notifications as "read" or "done".  Or maybe you will learn to just ignore notifications on github.com altogether -- personally I am not there yet(?).

While it is possible that I can come up with some more tweaks and workarounds over time; I think what we have now is pretty much as good as it gets.  Without Github getting their act together that is; but after waiting five years, I cannot count on that anymore.

**Comment by fosskers** [comment]
Thank you!

**Comment by benthamite** [comment]
In case this is useful to others, you may need to update `transient` if after updating `forge` you get an error on startup.

**Comment by benthamite** [comment]
Hi @tarsius, thank you for putting all this effort into supporting GitHub notifications with Forge.

Unfortunately, after experimenting with it for a while, I am unsure how one should work with this feature. I understand that syncing from Forge to GitHub is not possible, but even if I decide to ignore the GitHub inbox, there doesn’t seem to be a way of at least keeping the state of Forge notifications consistent over time.

Let’s consider an example. I first pull new notifications by running `n f n`. There is now one unread notification, which I open. Because I have `forge-notifications-github-kludge` set to `pending-if-unset`, the notification status now becomes “done”. So far, so good. But when I pull the notifications again, the notification marked as “done” is now “unread” again. Is this the expected behavior?

I previously used `gh-notify`, but it broke in October last year following some changes to the Forge codebase. That package Just Worked: reading a notification in Emacs would mark it as read in GitHub, and vice versa. I understand that the GitHub API leaves much to be desired (to put it mildly), but perhaps some ideas from that approach could be considered for Forge?

**Comment by tarsius** [comment]
I have to admit I haven't really migrated to using Forge for notifications yet.  Until I have done that, there are likely going to be bugs and features that haven't been adjusted yet to fully take advantage of what is possible now.

In response to your message I have fixed one rather obvious bug, see 1854837189cbfd2904752d586dc8cdc7a9850ee0.

Additionally I have noticed that I now[^1] can and should improve what issues and pull-requests are listed in the magit status buffer.  That probably should also become more configurable.

[^1] I.e., since "state" and "status" are tracked separately.

Some improvements should appear fairly soon, others might take longer.  I am working on a lot of different parts of Forge right now.  I'll also skip answering your questions for now.  Your feedback is useful (see above ;P), but its more productive if I just fix the issues users make me aware of, than if I spend time explaining what is not working right now and why.  Okay, I'll address some of it:

> There is now one unread notification, which I open. Because I have `forge-notifications-github-kludge` set to `pending-if-unset`, the notification status now becomes “done”.

It was set to "done" because of the, now fixed, bug that I mentioned above.

`forge-notifications-github-kludge` isn't relevant in this context.  It is only used to set the status of a topic/notification while *fetching* notifications.

I am not sure the `pending-if-unset` variant makes sense.  Since it doesn't work for you, stop using it.  Use `always-unread` or `pending-again`.  If the one you pick first doesn't work for you, try the other.  Then report why the better of the two isn't quite right for you either (though my response will likely be "I agree, but because the api is so bad it is not possible to do better".)

**Comment by benthamite** [comment]
Thanks, Tarsius: feel free to ignore any aspects of my feedback that you don’t feel like addressing right now. I’ll update the package, experiment a bit more and might provide further comments if I expect them to be potentially useful.

**Comment by benthamite** [comment]
@tarsius, to provide an update on this, with `forge` updated up to commit `28a55a7` and`forge-notifications-github-kludge` set to the default value of `pending-again`, I can summarize the current behavior as follows:

- the status of a notification that is read in the `*forge-notifications*` buffer will change from `unread` to `pending`.
- after running `n f n`, the status of the most recent notification will always be`unread` even if it had previously changed to `pending`.
- with the passage of time, as the user receives new notifications, notifications that previously refused to remain in a `pending` state after being read will now behave as expected, because they are no longer the most recent notification.

**Comment by tarsius** [comment]
> the status of *the most recent* notification will always be`unread`

Forge fetches all notifications "since" the date recorded for the latest already fetched notification. Gitlab seems to fetch everything *after* that date (though that doesn't matter here because we don't fetch notifications for Gitlab yet). But Github fetches all notifications since and including the provided date.

So we'll have to add a second to the recorded date for Github. That isn't hard to do (except for finding the correct functions among the see of time related functions in Emacs, but I've already done that). But I'll also do some related refactoring, which might delay this a few days.

**Comment by tarsius** [comment]
I've been working on this but have run into lots of issues and technical depth along the way. As a result it might take another week to finish this.

I am going to get the status from the topic API instead of the notification API. (That also lacks a done/pending boolean, but at least for unread/read this will simplify things.)

**Comment by tarsius** [comment]
> As a result it might take another week to finish this.

Instead I completely rearranged my apartment. :grin:

**Comment by tarsius** [comment]
With 715087aeb1ac35439015869004354471314dc211 and 93d3f2a8f9b6069765ad44088f1e6d7cfc135b70, this should now work fairly well.
