### ISSUE TITLE
Pull request subsection logs against local branch rather than remote branch

### ISSUE THREAD

**Issue by adrianparvino** [magit/forge#37]
I'll produce an MWE soon.

Take branch B, and a merge request exists from B to master.
the pull request subsection will display all commits starting branch B, to master, but also includes master's commit logs. This problem only seems to exhibit when the target is master.

**Comment by tarsius** [comment]
> The expected behavior is for the Git commit range to be `(remote/master .. pr)`, and not the local master.

That is one behavior that one might expect, but the actual behavior is also useful and intentional.

I *think* the situation you are describing is this:

```
* [pr-1] feature
* [origin/master] c
* [master] b
* a
```

and you are arguing that instead of

```
Pull requests
#1 add feature
xyz [39] feature
abc [origin/master] c
```

one should see

```
Pull requests
#1 add feature
xyz [39] feature
```

I actually think the former is better.  It allows you to see that your local `feature` branch has two additional commits compared to your local `master` branch.  While the `c` commit was not actually created as part of the `pr-1` pull-request merging that into `master` would never-the-less be what would cause it to become part of `master`.

Of course you shouldn't actually do that, as doing so would result in:

```
* [master] Merge branch 'feature'
|\
| * [pr-1] feature
| * [origin/master] c
|/
* b
* a
```

instead of

```
* [master] Merge branch 'feature'
|\
| * [pr-1] feature
|/
* [origin/master] c
* b
* a
```

Seeing the `abc [origin/master] c` in the log for `pr-1` makes it less likely that you make that mistake.

Even ignoring this it still makes sense to show `master..PR` instead of `origin/master..PR` because the `PR` also refers to a local branch if possible (here `pr-1`).  Locally you usually only manipulate local branches (except when pushing), so it makes sense to compare local branches while you do things such as merging, rebasing and manipulating commits from a pull-request.
