### ISSUE TITLE
forge create pull request from issue can't find feature branch (possible ivy integration issue?)

### ISSUE THREAD

**Issue by vigilancetech-com** [magit/forge#371]
I cloned someone else's repo off github (org-brain)

I did forge-pull on it.  Everything appeared to work correctly.  Now I can see the current issues and PRs

I created a branch in magit.  It shows up as the current branch in magit status on the upper left

I made my changes and committed them.

I went to make my create pull request for issue (spacemacs keys @-c-u from the magit status screen)

('m assuming) Ivy doesn't offer me the newly created branch neither for source nor target.   I can't type in the right branch name either.  Says something like "no match"

I restarted emacs and tried again.  Nothing.  Problem still remains.

**Comment by tarsius** [comment]
You have to push the feature branch to github first.

**Comment by vigilancetech-com** [comment]
So github's API doesn't support creating a PR off the local repo?

**Comment by tarsius** [comment]
Of course not. Github does not have access to your computer. You have to push your commits to their servers because otherwise they have no way of even just knowing that those commits exist.

Now, whether Forge should detect this situation and ask you whether you want to push first, that is a different question.
