### ISSUE TITLE
Error: Cannot insert ("N" "Forge" forge-dispatch) into magit-dispatch; % not found

### ISSUE THREAD

**Issue by ashton314** [magit/forge#388]
This seems to happen when I open up Magit in a repository that doesn't have any issues/topics/etc. As an example, my [dotfiles](https://github.com/ashton314/dotfiles) doesn't have any issues or prs, and opening Magit seems to make it blow up.

I do have `evil-mode` and `evil-collection` turned on, but these don't seem to be affecting it: I tried loading just magit and forge and still got the same problem.

I wasn't able to generate a trace-back, even after flipping on the error reporting. :/ please let me know if you need help reproducing this issue.

**Comment by ashton314** [comment]
Ok, I did some manual bisecting, and it looks like this was introduced in commit `9bec1c54ab0705eb68ae4aa6c8a0498999a018f6` on magit. I'll open an issue there 'cause this doesn't seem to be caused by forge. Sorry about that.

**Comment by tarsius** [comment]
The suffix that was previously bound to `"%"` is now bound to `Z` instead so "place a new entry after the %-entry" does work anymore. Somewhere in `evil-collection` the equivalent this change has to be made:

```diff
-(transient-append-suffix 'magit-dispatch "%" '(...))
+(transient-append-suffix 'magit-dispatch '(0 -1 -1) '(...))
```

Using `(0 -1 -1)` is a better way of saying "at the end of that section", then use `"Z"`, which would come with the same risk as `"%"` did and see where that got us.

I did not spot the respective place in `evil-collection`. So I am pinging @condy0919 instead of opening a pull-request.

**Comment by basil-conto** [comment]
> The suffix that was previously bound to `"%"` is now bound to `Z` instead so "place a new entry after the %-entry" does work anymore. Somewhere in `evil-collection` the equivalent of this change has to be made:

As the title of this issue suggests, the "after `%`" binding is not  happening in `evil-collection`, but in Forge itself:

https://github.com/magit/forge/blob/93c8005ce72a765b8be189c43962cee084f51880/lisp/forge.el#L83-L84

This is also the case in `magit-annex`:

https://github.com/magit/magit-annex/blob/17e5e60b59eac3cf5938c1b22c29458c0d694b0a/magit-annex.el#L270-L275

Which gives rise to the analogous message

```
Cannot insert ("@" "Annex" magit-annex-dispatch-or-init) into magit-dispatch; % not found
```

Have I misunderstood something?

Another question regarding commit https://github.com/magit/magit/commit/9bec1c54ab0705eb68ae4aa6c8a0498999a018f6 : I see that `%` was renamed to `Z` in `magit-dispatch`, but not in `magit-mode-map`.  Was that intentional?

Thanks.

**Comment by condy0919** [comment]
> The suffix that was previously bound to `"%"` is now bound to `Z` instead so "place a new entry after the %-entry" does work anymore. Somewhere in `evil-collection` the equivalent of this change has to be made:
> 
> ```diff
> -(transient-append-suffix 'magit-dispatch "%" '(...))
> +(transient-append-suffix 'magit-dispatch '(0 -1 -1) '(...))
> ```
> 
> Using `(0 -1 -1)` is a better way of saying "at the end of that section", then to use `"Z"`, which would come with the same risk as `"%"` did and see where that got us.
> 
> I did not spot the respective place in `evil-collection`. So I am pinging @condy0919 instead of opening a pull-request.

Thanks for pinging.

**Comment by tarsius** [comment]
> but in Forge itself:

Ah right, I overlooked that.

> Another question regarding commit https://github.com/magit/magit/commit/9bec1c54ab0705eb68ae4aa6c8a0498999a018f6 : I see that `%` was renamed to `Z` in `magit-dispatch`, but not in `magit-mode-map`.  Was that intentional?

Yes. In a keymap we can have two bindings and users just press which ever they want and don't have to worry about the other, while in the menu we don't want to show the same command twice.

**Comment by basil-conto** [comment]
Thanks for the quick fix!  Do you also intend to patch `magit-annex` accordingly, or should I submit a PR?

> > Another question regarding commit [magit/magit@9bec1c5](https://github.com/magit/magit/commit/9bec1c54ab0705eb68ae4aa6c8a0498999a018f6) : I see that `%` was renamed to `Z` in `magit-dispatch`, but not in `magit-mode-map`.  Was that intentional?
> 
> Yes. In a keymap we can have two bindings and users just press which ever they want and don't have to worry about the other, while in the menu we don't want to show the same command twice.

Right, thanks.

**Comment by tarsius** [comment]
I've done that too now.

**Comment by tarsius** [comment]
Thanks for the pocks. :grin:

**Comment by basil-conto** [comment]
Sorry, what's a pock? :)

**Comment by tarsius** [comment]
Err .... "poke".

**Comment by basil-conto** [comment]
Ah, thanks for responding so quickly to pokes! ;)

**Comment by ashton314** [comment]
A pock is a poke with one of these:
![image](https://user-images.githubusercontent.com/2874507/130103652-b33cd732-ba5d-4b7e-bc1a-518c376d9295.png)

**Comment by mangkoran** [comment]
Thank you for showing the relevant issue!
