### ISSUE TITLE
Is it necessary to repeat the pullreq identifier at the branch's HEAD commit?

### ISSUE THREAD

**Issue by vermiculus** [magit/forge#40]
See example:

```
#39 Allow any username in url regexp
d3bf962 39 Introduce username-regex to ...
ae8e8e2 Extract regexp variables in forge--url-regexp
```

The `39` on the second line seems redundant; I can't think of a situation where `39` would *not* be at `d3bf962` (or whatever commit is first in that section).  Am I missing something or can this duplication be removed?

This may be non-trivial as it seems `magit-insert-log` is responsible for this.

**Comment by tarsius** [comment]
Necessary? No, but does it hurt to do it?

> The `39` on the second line seems redundant; I can't think of a situation where `39` would *not* be at `d3bf962` (or whatever commit is first in that section).

1. Contributor pushes new commits.
2. Maintainer does `f a` but not `f y`.

> Am I missing something or can this duplication be removed?

I don't actually want to remove it because then we would lose the ability to spot an inconsistency resulting from the above events.

Even if such an inconsistency were somehow made impossible I would not want to remove it.  The pull-request refs are displayed are displayed everywhere; it would be weird not to display it here too.

**Comment by vermiculus** [comment]
> I don't actually want to remove it because then we would lose the ability to spot an inconsistency resulting from the above events.

Thanks for the use-case – and I agree that a way to detect it is useful. I wonder if it's useful enough to call out more explicitly, but I'll leave that to a separate future request from someone else :-)
