### ISSUE TITLE
Option to not show closed PRs in forge-checkout-pullreq

### ISSUE THREAD

**Issue by aaronjensen** [magit/forge#42]
It looks like `forge-checkout-pullreq` shows all (or at least many closed and open) prs. I very rarely want to checkout a closed PR. Is it possible to filter this (and possibly even the PR list in the status buffer) to only include open PRs?

Thanks!

**Comment by vermiculus** [comment]
It's probably something that could/should be controlled by prefix argument (perhaps instead of configuration). `C-u M-x forge-checkout-pullreq` would display everything where the default behavior would apply any filtering configured for the repository.

Magithub took the approach of a list of filter-functions to run the topic-list through – would that be the approach we'd want to take here? My impression is that it was a little overkill, but it *did* allow more complicated filters like 'don't show this label unless it also has this label' – something I did end up using once the repo had many, many issues and requests on it.

**Comment by Wilfred** [comment]
A similar option for issues would also be very useful.
