### ISSUE TITLE
Consistent Forge error on Nyxt repo

### ISSUE THREAD

**Issue by tvraman** [magit/forge#442]
On Repo: https://github.com/atlas-engineer/nyxt.git I get error in process filter:  HTTP Error: 502, "Bad gateway", "/graphql", ((data) (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `ABA0:0D6A:19F28B:1AE8A9:61AE5566` when reporting this issue.")))) [2 times]

**Comment by tarsius** [comment]
Two days ago that kept happening to me for the magit repository. It went away an hour later or so. The same will probably happen here. (Normally when this happens immediately trying another two times or so does the trick.)

You could ask Github for more information but I suspect that if they were we willing to give us some useful information they would have done it upfront instead of essentially saying "something went wrong, maybe if you ask nicely we will give you more information".

**Comment by tarsius** [comment]
(Or in other words; we had similar reports in the past and I still don't know what I could do to make this not happen.)

**Comment by tvraman** [comment]
Jonas Bernoulli ***@***.***> writes:

reason I blamed magit ( incorrectly)> (Or in other words; we had similar
reports in the past and I still
is that after magit/forge failed multiple times, I was able to create
the issue using the command-line "gh" tool.

> don't know what I could do to make this not happen.)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
> reason I blamed magit ( incorrectly) is that after magit/forge failed multiple times, I was able to create the issue using the command-line "gh" tool.

That was a reasonable conclusion (when replacing "magit" with "forge") but here forge and gh perform very different tasks. Complex GraphQL query vs. small PUT request. The problem seems to be that the complex request somehow times out on their end.
