### ISSUE TITLE
Quoted blocks removed when visiting topics

### ISSUE THREAD

**Issue by PuercoPop** [magit/forge#45]
In particular I've encountered this behaviour in this Pull Request

https://github.com/stumpwm/stumpwm/pull/544#issuecomment-449791330

![image](https://user-images.githubusercontent.com/387111/50526343-66194f00-0aaf-11e9-89e7-b0271d3815a2.png)

Note that there is a line with one empty space where the quoted block should be. Also I verified in the SQLite database that the quoted blocks are present

**Comment by vermiculus** [comment]
This might be a gfm-like setting; did you check any variables that might be hiding markup? (My wife is hoarding my laptop right now but I *think* it's labeled as some sort of 'clean' mode.)

**Comment by PuercoPop** [comment]
> This might be a gfm-like setting; did you check any variables that might be hiding markup? (My wife is hoarding my laptop right now but I think it's labeled as some sort of 'clean' mode.)

I can't find anything that might be doing so, but you've given me an idea. It may be that markdown-mode may be interpreting the content as the lang of the code-block as the whole quoted text is one line with triple backticks

**Comment by PuercoPop** [comment]
@vermiculus Yes, I quote with `>` but I don't control how other people use markup. Thanks for the pointer of `markdown-hide-markup-in-view-modes` but that didn't do the trick. Although I suspect the 'bug' is more likely to be in markdown-mode, I'll look into it. Thanks for the pointers again!

**Comment by vermiculus** [comment]
I find it unlikely that markdown-mode will ever do what you're asking it to do (which is to effectively ignore the most basic syntax rules of markdown!), but you might be able to hack the regular expressions markdown-mode uses to recognize quote blocks. You'll have better luck convincing others to use markdown correctly, I think :-)

It is odd though that from getting the fontified text in `forge--fontify-markdown` to inserting it in `forge-topic-refresh-buffer`, we seem to loose the content in ```` ```triple quotes``` ````.

**Comment by tarsius** [comment]
`one`

``two``

```tree```

**Comment by tarsius** [comment]
`markdown-mode` sets `invisible` to `markdown-markup` for all of

    ```text```

If the delimiters are just one or two backquotes, then it doesn't do that. At least `gfm-mode` shouldn't treat three backquotes the same as two because three opening *and* closing backquotes on the same line is valid gfm syntax and in that case the `text` part is not part of the markup its the content, unlike in

    ```language
    content
    ```

where `language` is part of the markup.

----

The reason that setting `markdown-hide-markup-in-view-modes` is that it only affects the buffer in which the parsing happens. If we copy text from there into another buffer, then the `invisible` property still has the normal affect. As a workaround do this in the topic buffer:

```emacs-lisp
(remove-from-invisibility-spec 'markdown-markup)
```

**Comment by tarsius** [comment]
Fixed with https://github.com/jrblevin/markdown-mode/pull/492.
