### ISSUE TITLE
Overrides magit's new branch shortcut (b n)

### ISSUE THREAD

**Issue by Atemu** [magit/forge#450]
In my Spacemacs installation, forge overrides the new branch shortcut (`b n`) with pull-request. This is not desirable behaviour as I still want to be able to create local branches without having a github workflow forced upon me.

Forge should use a different shortcut but it seemingly already does? `b f` has the same labelling.

**Comment by tarsius** [comment]
`... n` was chosen as the binding for forge commands because it does not conflict in most of the transient prefix commands to which forge adds its own variant.

When not using (spacemacs) evil bindings, then `b n` does not conflict with an existing command. "Create and checkout" is `b c` and "only create" is `b C`.

I believe spacemacs uses `evil-collection`. And since https://github.com/emacs-evil/evil-collection/commit/88242de2a6b8e9c1b535365f54e90042f7b4daee `evil-collection` prevents `forge` from adding its default bindings. So probably you just have to update `evil-collection`.

**Comment by Atemu** [comment]
Oh! Didn't know `b n` was an evil thin. `b C` still works even (eventhough it's not shown). Thanks!
