### ISSUE TITLE
Topic Title edits not taken into account

### ISSUE THREAD

**Issue by shindere** [magit/forge#456]
If the title of a topic is changed in the web interface of GitHub,
it seems forge does not take this into account and will continue to
display the initial title rather than the new one, even after a pull.

Is this a known behaviour?

What about edits of posts? Are they taken into account?

**Comment by tarsius** [comment]
Forge depends on Github marking modified topics as modified. Unfortunately Github considers certain modifications not to be modifications. Might be a bug, misguided "optimization" or intentional crippling of third-party tools, I don't know and asking/informing them about issues usually doesn't do anything. There isn't really much I could do about that except fetching everything every time, which obviously isn't feasible.

If you know that some topic was modified but the modifications don't show up, or you suspect that something was modified, then you can fetch that topic individually using `n f f`.

**Comment by shindere** [comment]
Jonas Bernoulli (2022/01/24 04:39 -0800):
> Forge depends on Github marking modified topics as modified. Unfortunately Github considers certain modifications not to be modifications. Might be a bug, misguided "optimization" or intentional crippling of third-party tools, I don't know and asking/informing them about issues usually doesn't do anything. There isn't really much I could do about that except fetching everything every time, which obviously isn't feasible.
> 
> If you know that some topic was modified but the modifications don't
> show up, or you suspect that something was modified, then you can
> fetch that topic individually using `n f f`.

Thanks. For this time, it seems that pulling the new stuff fixed the
issue (the PR now appears with the right title).

Is there a way to delete just the DB for one repository and fetc
everything again?

I didn't dare to delete the repository becuase I didnt want theorktree
and repository to be deleted, jsut the database with the topics etc.

**Comment by tarsius** [comment]
Yes you can delete a repository from the database using `M-x forge-remove-repository`.

There's actually just one database for all repositories. So deleting a git repository would not actually delete "its forge database".

**Comment by shindere** [comment]
Jonas Bernoulli (2022/01/24 15:03 -0800):
> Yes you can delete a repository from the database using `M-x
> forge-remove-repository`.

Okay thanks!

> There's actually just one database for all repositories. So deleting a
> git repository would not actually delete "its forge database".

Understood, thanks. IT's rather the converse whichmade me a bit nervous,
the fact that removing a repository (from the database) would also
assume one wants it to be removed from the filesystem. It's good to know
it's not the case!
