### ISSUE TITLE
List of assigned issues is empty but should not

### ISSUE THREAD

**Issue by shindere** [magit/forge#457]
When visiting the list of assigned issues, the buffer is empty while I do
have assigned issues.

Could it be because the auth token changed between gthe moment when*those
issues were assigned and now?

Looks unlikely to me but I can't think of another cause at the moment.

**Comment by tarsius** [comment]
The token doesn't matter.

I suspect the reason is the same as in  #457. Try `n f f` here too.

**Comment by shindere** [comment]
It works now. Thanks.

Feel free to close!

**Comment by shindere** [comment]
I still believe the token matters.

Indeed, I tried to use the same token on two different machines to fetch
the same repository and work on it from two different places but I am
noticing that a topic that has been fetched on one machine is then no longer
seen on the other machine.

That does actually not look to surprising to me becuase I am assuming
that it's the token which is used by GitHub to determine what is
new since the last fetch. Is that correct?

Am I thus correct that, just from a functional point of view (let alone
security reasons) a token must not be shared between two machines
from which one wants to work on the same repository?

**Comment by tarsius** [comment]
I don't use more than one machine, so that might be part of the reason things don't just work.

You shouldn't synchronize the database manually. The only thing that won't eventually be in sync are the notifications.

I realize now that you might be relying too much on fetching notifications instead of fetching everything that was updated in the repository that you are currently working on. Personally I almost exclusively use `f n` (for each repository I am currently working on) and only very seldomly `f N`.

**Comment by shindere** [comment]
Thanks! I use `f n` too, never used `f N`!

**Comment by shindere** [comment]
Is `f n` supposed to remeber what has been fetched last time (in terms
of issues and PRs) and updtate from that point, independently of
notifications?

I think that's not what happens for me but I can perform more precise
tests to clarify the situation if needed.

**Comment by tarsius** [comment]
Yes, that's what is supposed to happen.

**Comment by shindere** [comment]
Okay I tested once more and, this time, it did work.

No idea what happened last time but it's great that the feature works
that way.

Really sorry for the noise.

**Comment by tarsius** [comment]
No problem.
