### ISSUE TITLE
Imprecise error message on missing forge setup

### ISSUE THREAD

**Issue by Kha** [magit/forge#460]
I set up forge for the upstream repository, but did not notice that `forge.remote` was still set to my fork, leading to the following confusing interaction:
```
Cannot use ‘forge-create-pullreq’ in "/home/sebastian/lean/lean/" yet.
Use `M-x forge-add-repository' before trying again.
```
Doing just that (again):
```
user-error: https://github.com/leanprover/lean4.git is already tracked in Forge database
```
The first line should probably mention the repo URL that has not been set up yet to avoid the confusion

**Comment by tarsius** [comment]
> I set up forge for the upstream repository, but did not notice that `forge.remote` was still set to my fork, leading to the following confusing interaction:

Please provide more information about that part. Did you (intentionally?) setup forge to use your fork? And did that work for a while? If so, then what did you do that caused it to stop working?

**Comment by Kha** [comment]
I tried to use forge for the first time, to open a pull request in the upstream repo. Therefore I ran `forge-add-repository` once, changing the default repo URL (my fork's) to the upstream repo in the prompt. Then I tried opening the pull request again, not noticing that I was still in the state
![image](https://user-images.githubusercontent.com/109126/152521020-6bfcac11-c921-453d-9c95-19a3850ff5b5.png)
This triggered the "Cannot use ‘forge-create-pullreq’ in "/home/sebastian/lean/lean/" yet." error again, which was confusing to me because I *had* just set up forge in that directory, just not for the remote magit expected, which is information missing from the message.

**Comment by tarsius** [comment]
A few months ago I taught Magit to better deal with the (to me) surprisingly common practice of naming the fork "origin" even though I think this is wrong. (I name the original remote "origin", i.e. the upstream. Naming the upstream "upstream" instead is also fine. What doesn't make sense to me is call the fork, i.e. the *copy*, the "origin[al]". It seems to me that a copy is *the opposite* or the original, so naming it "origin" seems... a bit misguided.

But as I said I learned that many people do that, so I will have to deal with it here too. I'll have to think about it more though because I put the ideas I am having so far into action, then we are getting dangerously close to "setup wizard" territory again.

**Comment by Kha** [comment]
I completely agree with you on naming, but in practice I just follow what the command line tools do. `hub` used `origin` and `<user>` (afair), `gh` uses `upstream` and `origin`.
