### ISSUE TITLE
Drafted issue deleted unrecoverable on failed submission 

### ISSUE THREAD

**Issue by shonfeder** [magit/forge#493]
I expected to be able to draft a new issue using using `forge-create-issue` (this usually works), saving my progress along the way (I was, it was saving to `".git/magit/posts/new-issue" 121L, 4300C written`). 

But when I went to submit the buffer with `C-c C-c`, the buffer was removed and the file deleted! :(

I don't know how to reproduce it, but here's the log messages I see:

```
Wrote /my/path/tnt/doc/lang.md
"doc/lang.md" 1891L, 48347C written
Wrote /my/path/tnt/.git/magit/posts/new-issue
".git/magit/posts/new-issue" 121L, 4300C written
.git/magit/posts/new-issue removed from cache
error in process filter: process-file: Setting current directory: No such file or directory, /my/path/tnt/.git/magit/posts/
error in process filter: Setting current directory: No such file or directory, /my/path/tnt/.git/magit/posts/
```

This seems like a quite scary issue to me, as I lost several hours of work.

**Comment by tarsius** [comment]
> This seems like a quite scary issue to me, as I lost several hours of work.

The file likely wasn't deleted but moved to the trash. (See `delete-file`'s docstring and go from there, if you don't know where the trash is.)

**Comment by tarsius** [comment]
Forge makes an API request which either fails (in which case it calls `forge--post-submit-errorback`) or succeeds (in which case it calls `forge--post-submit-callback`).

The former function never deletes the file. The latter does because the API response told it that storing the information succeeded and we therefore don't have to hold on to it locally.

Did you verify that the issue was not actually created (using the web interface)? Nothing in the output you provided says it didn't. I think it succeeded and then something else went wrong locally.

**Comment by shonfeder** [comment]
Thanks for the hint about the trash. I didn’t find it there unfortunately… BUT that’s because you are right that it was submitted successfully! I’m very sorry I didn’t check GitHub before concluding the work was lost! I didn’t see the magit forge PRs updated (which they usually do) and simply concluded failure from that. I was probably working too late on top of everything :)

Sorry for the false alarm and thanks very much for helping me debug and for this amazing software.
