### ISSUE TITLE
Incompatible with stable magit version

### ISSUE THREAD

**Issue by astoff** [magit/forge#498]
I have magit version 3.3.0 installed (the latest available from NonGNU ELPA) and forge from MELPA. When I do `(forge-dispatch)`, I get this error:

```
transient-setup: Wrong type argument: sequencep, #[257 "\300\301!\207" [forge--get-remote t] 3 "

(fn _)"]
```

The problem vanishes if I update magit to the current MELPA version. However, the forge package on MELPA claims to be compatible with magit 3.3.0, and in fact I would usually expect packages to be compatible with the latest official release of their dependencies.

**Comment by tarsius** [comment]
My guess is that you updated one of the two packages before switching to another Emacs release and the other afterwards. Uninstall both packages (and to be safe `ghub` and `transient` as well), exit Emacs, restart Emacs and reinstall the packages.

**Comment by AkibAzmain** [comment]
@astroff: How did you install?  I can't install forge because it depends on **"magit-20220621"**.

**Comment by astoff** [comment]
The following minimal init file reproduces the problem (forge installed from Melpa, magit from GNU ELPA):

``` emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(setq package-archive-priorities '(("gnu" . 2) ("nongnu" . 1) ("melpa" . 0)))
(package-refresh-contents)
(package-install 'magit)
(package-install 'forge)
```

On the Melpa website, it's claimed forge-2022something requires magit-2022something, but after starting up Emacs with the above init file I get magit-3.3.0 and forge-2022something. And my forge-pkg.el indeed mentions `(magit "3.3.0")` as a dependency.

**Comment by tarsius** [comment]
I just re-read the initial description and I agree the development version of forge is incompatible with the development version of magit. This is not unexpected, so if you want to use melpa forge, you also have to use melpa magit.

> The following minimal init file reproduces the problem (forge installed from Melpa, magit from GNU ELPA):

Forge gets installed from melpa because that is the only place it is available from. It appears that archive priorities take priority over minimal versions, which seems unfortunate. You can probably override it using `package-pinned-packages`.

But I would recommend you simply don't set `package-archive-priorities`.

**Comment by astoff** [comment]
> the development version of forge is incompatible with the development version of magit

Okay, if that's intended then I'll close the issue. But in this case I think it would be nice to have a "stable" version of forge on ELPA. Melpa-stable is kind of unusable, as is well known.

> But I would recommend you simply don't set package-archive-priorities.

I do this so I don't get random package updates for each small change done upstream, at least for packages on ELPA. It works fine, since typically a package depends only on the stable version (a.k.a. numbered release) of its dependencies.

**Comment by tarsius** [comment]
> Okay, if that's intended then I'll close the issue.

Well, it's not *intended* in the sense that I broke compatibility for the sake of breaking compatibility. It is *expected* that in order to improve features and/or internal architecture, changes have to be made that are not backward compatible.

> But in this case I think it would be nice to have a "stable" version of forge on ELPA. Melpa-stable is kind of unusable, as is well known.

This will never happen because RMS won't allow adding this package to GNU Elpa or even just nonGNU Elpa, because this package "promotes the use of non-free software/services".

**Comment by AkibAzmain** [comment]
> This will never happen because RMS won't allow adding this package to GNU Elpa or even just nonGNU Elpa, because this package "promotes the use of non-free software/services".

We can split the package into two packages, one free, another nonfree.  However I think that it should be done after Forge becomes mature enough, otherwise it would just become a burden.

**Comment by tarsius** [comment]
Yes at this point this would be just a burden. We will see what the future brings.
