### ISSUE TITLE
Editing Review-Requests field sometimes doesn't work

### ISSUE THREAD

**Issue by Lenbok** [magit/forge#705]
Magit v4.1.0-4-g05d7565f, Transient 0.7.5, Forge 0.4.3, Git 2.43.0, Emacs 29.4.50, gnu/linux

I created a new PR using Forge
I then viewed the PR in order to request review. Placed cursor on the "Review-Requests" line and did `C-c C-e`

Observed behaviour:
- `eieio-oref@closql-object: Wrong type argument: (or eieio-object cl-structure-object oclosure), nil`

Expected behaviour:
- let me set the reviewer.

Interestingly, if I go to the PR "State" field and `C-c C-e` and then Quit, whatever that does allows the Review-Requests field to be edited, but after the edit there is a `nil` shown.

**Comment by utlandr** [comment]
I am also having this issue

**Comment by tarsius** [comment]
I was able to reproduce once, but not anymore.

This error occurs because `(transient-suffix-object)` (via the command definition in `forge--topic-set-state-command`) returns `nil`. It shouldn't be able to do that. Because the command was not invoked from a prefix, the last code-path is taken. `(get command 'transient--suffix)` (via `transient--suffix-prototype`) should return non-`nil`. I suspect that when this does not work, its because the `transient--suffix` property of `command` (which is the value of `this-command` in this case), doesn't have the `transient--suffix` property set.

I don't understand how that could happen. It could have something to do with autoloads and/or compilation order somehow messing up compilation.

Please check if `forge-autoloads.el` exist next to the forge libraries and if it does, post the code surrounding `(autoload 'forge-topic-menu "forge-topic" nil t)` from that.

I observe this possibly related issue. If I exit emacs, touch `forge-topic.el`, to trigger my `autocompile` package into recompiling that library before it is loaded, then I get this compilation error:

```
forge-topic.el:1309:2: Error: Symbol's value as variable is void: forge--topic-menus-group
```

That too is surprising because that variable is defined in that file, further up.

----

I suspect you can fix this issue by recompiling `forge-topic.el` and restarting emacs.
