### ISSUE TITLE
forge-pull fails when interactively creating a Github token

### ISSUE THREAD

**Issue by parhamdoustdar** [magit/forge#73]
When I do `forge-pull`, everything goes well, until the point where I get this in my `*Messages*` buffer:

```
 Wrong type argument: stringp, #[0 "\301\242\203
�\300\301\242\300\242!\240\210\300\242\207" [("RETRACTED") (nil)] 3]
```

When I turn on `debug-on-error`, i see this at the top:

```
  encode-coding-string(#f(compiled-function () #<bytecode 0x42dc6271>) utf-8)
  ghub--auth("api.github.com" forge "parhamdoustdar" nil)
```

Thanks for creating Forge, it's going to be awesome once I can use it!

**Comment by tarsius** [comment]
`#[ ...]` is a byte-compiled function. `encode-coding-string` can only be called inside `ghub--auth` with a function as argument if `ghub--token` returns a function. Some `auth-source` backends wrap the secret in a function that returns the secret instead of returning the secret directly.

1. I am guessing that is done as a security measure, but it does not work. The backtrace you posted did contain you token! I retracted that, but that doesn't actually work either. You have to immediately delete that token on Github.

2. `ghub--token` now ends with `(if (functionp token) (funcall token) token))`, which should always return the token. Therefore updating `ghub` should fix this issue.

**Comment by vermiculus** [comment]
@parhamdoustdar As soon as possible, you should revoke and re-issue the token you accidentally published here.

**Comment by parhamdoustdar** [comment]
Thanks for noting that! I removed the token. It did look like a token, but
I wasn't sure at the time. :-)
I'll just wait for the ghub update then.

**Comment by tarsius** [comment]
> I'll just wait for the ghub update then.

No need to wait, just install it. (What version are you currently using?)

**Comment by parhamdoustdar** [comment]
I'm using the latest version in melpa, which is 20190107.1937.

**Comment by tarsius** [comment]
Do you use some third-party `auth-source` extension?

Try adding some debug statements to `ghub--token` to figure out why it returns a function.

**Comment by parhamdoustdar** [comment]
I'm using tokens stored in `~/.authinfo.gpg` which always returns a
function when you use the `auth-source-search` function to look-up
authentication info. I have code in my own start-up scripts that retrieves
and uses the secrets from that file using `auth-source`.

**Comment by tarsius** [comment]
> I'm using tokens stored in `~/.authinfo.gpg` which always returns a function when you use the `auth-source-search` function to look-up authentication info.

`ghub--token` however evaluates that function and then returns the value returned by that. Somehow it doesn't do that for you... maybe, which is why I suggested adding debug statements that might shed some light on what is going on.

> I have code in my own start-up scripts that retrieves and uses the secrets from that file using `auth-source`.

Does that code use advice? Maybe your additions are what is causing this issue. Try to reproduce the issue with your custom code removed.
