### ISSUE TITLE
forge-pull results in parse error

### ISSUE THREAD

**Issue by wedens** [magit/forge#8]
When I try to do `forge-pull` on https://github.com/typelevel/cats-effect/ repo, it results in:

```
error in process filter: ghub--signal-error: peculiar error: ((message . "Parse error on \"/\" (error) at [6554, 54]") (locations ((line . 6554) (column . 54))))
error in process filter: peculiar error: ((message . "Parse error on \"/\" (error) at [6554, 54]") (locations ((line . 6554) (column . 54))))
```

If I reopen magit-status, PRs and issues are there.

I've updated all packages to the latest versions (at the moment of creating the issue).

**Comment by alphapapa** [comment]
I got an error similar to @rychipman's.  I tried to copy it, but the lines were so long that Emacs froze for so long that I couldn't copy it.

**Comment by knobo** [comment]
#metoo 

``` 
Pulling notifications...
error in process filter: ghub--signal-error: peculiar error: ((message . "Parse error on \"+\" (error) at [3494, 50]") (locations ((line . 3494) (column . 50))))
error in process filter: peculiar error: ((message . "Parse error on \"+\" (error) at [3494, 50]") (locations ((line . 3494) (column . 50))))
Pulling myaccount/myrepo
error in process filter: ghub--graphql-walk-response: Invalid function: string>
error in process filter: Invalid function: string>
```

**Comment by tarsius** [comment]
> When I try to do `forge-pull` on https://github.com/typelevel/cats-effect/ repo

That's probably because of the trailing slash.  I just tried with git@github.com:typelevel/cats-effect.git and there was no parse error.

I'll have to look into droping such trailing slashes.

> Parse error on \"+\"

Does the name of the repository somehow involve "+"?

**Comment by wedens** [comment]
> That's probably because of the trailing slash. I just tried with git@github.com:typelevel/cats-effect.git and there was no parse error.

In a git remote I have https://github.com/typelevel/cats-effect.git. Seems like it fails on something else.

**Comment by aaronjensen** [comment]
Same here, no trailing slash and it's an ssh origin.

```
error in process filter: ghub--signal-error: peculiar error: ((message . "Parse error on \"+\" (error) at [1802, 48]") (locations ((line . 1802) (column . 48))))
error in process filter: peculiar error: ((message . "Parse error on \"+\" (error) at [1802, 48]") (locations ((line . 1802) (column . 48))))
```

**Comment by jimeh** [comment]
I have the same issue too when pulling notifications:

```
Pulling notifications...
error in process filter: ghub--signal-error: peculiar error: ((message . "Parse error on \"+\" (error) at [14393, 48]") (locations ((line . 14393) (column . 48))))
error in process filter: peculiar error: ((message . "Parse error on \"+\" (error) at [14393, 48]") (locations ((line . 14393) (column . 48))))
```

Since it seemed to be failing on a `+` symbol, I figured I'd try fetching down the list of notifications myself from GitHub's API to try and debug what's going on. I'm not sure if this is the same request that Forge performs, but there's some code that make it look like it might be:

```
curl -H "Authorization: Bearer <TOKEN>" "https://api.github.com/notifications?all=true"
```

And the only instances of `+` in the whole response was within a the `repository.contents_url` key's value of all notifications:

```js
{
  "id": "...",
  ...
  "repository": {
    ...
    "issue_comment_url": "https://api.github.com/repos/healiosuk/panacea/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/cantino/mcfly/contents/{+path}",
    "compare_url": "https://api.github.com/repos/cantino/mcfly/compare/{base}...{head}",
    ...
  }
  ...
}
```

Since all other `{...}` placeholders do not include a `+`, this might the source of the problem. Hopefully this helps a bit with narrowing down the issue.

**Comment by tarsius** [comment]
> Does the `(locations ((line . x) (column . y))` part indicate anything?

If nothing else, it indicates that the error comes from a GraphQL request not the REST request @jimeh tried.  A buffer named something like " *url N*" should still exist (the name begins with a space and contains the substring "url" and a number, not sure about the actual format).  Maybe multiple such buffers exist, look for the one with the highest N (probably).

----

Unfortunately the GraphQL API does not support notifications.  Forge first makes a REST request to get all notifications.  Unfortunately that does not contain all the required information.  So Forge builds a GraphQL request from the REST response.  That basically looks like

```
(query
 (KEY1 . QUERY)
 (KEY2 . QUERY)
 ...)
```

QUERY is basically the same in each case except that `name`, `owner` and `number` are different.  The KEYs are based on the IDs that Forge would use for the respective issues.  We cannot use those IDs directly because they would not be valid as "alias names" in GraphQL requests.

The IDs are supposed to be base64 encoded strings, though that is not completely certain.  Such base64 strings then have to be prefixed with "_" to make sure it doesn't begin with a number and "=" is replaced with "_".  I suspect the issue is that somehow a "+" slips through.

I cannot reproduce that with the repositories that you mention because what repository you fetch is actually irrelevant.  The error occurs when fetching notifications and I obviously won't get the same notifications that you get.

Could you please insert this debug-statement into `forge--ghub-massage-notifications` and post any lines printed by that:

``` emacs-lisp
diff --git a/lisp/forge-github.el b/lisp/forge-github.el
index 7322877..9881285 100644
--- a/lisp/forge-github.el
+++ b/lisp/forge-github.el
@@ -350,6 +350,12 @@ (defun forge--ghub-massage-notification (data forge githost)
            (name   (oref repo name))
            (id     (forge--object-id repoid .id))
            (key    (intern (concat "_" (replace-regexp-in-string "=" "_" id)))))
+      (when (or (string-match-p "\\+" repoid)
+                (string-match-p "\\+" id)
+                (string-match-p "\\+" key))
+        (message "> %s/%s#%s %S %S %S"
+                 owner name number
+                 repoid id key))
       (list key repo
             (and (memq type '(pullreq issue))
                  `(,key
```

(Looking at the request as described in the beginning should also work... assuming you can find the buffer.)

**Comment by flodiebold** [comment]
@tarsius Here's an example that happens for me: `rust-lang/rfcs#1203`. `repoid` is `Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTE3NTI3OTg5`, the issue id is `89835430`.

```
(forge--object-id "Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTE3NTI3OTg5" "89835430")
"Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTE3NTI3OTg5OvPfN+eN9A=="
```

`forge--object-id` tries (and succeeds) to base64-decode the issue ID, even though it's not encoded, and that seems to result in the problem in this case. I don't really understand why it's doing the decoding though.

**Comment by tarsius** [comment]
> `forge--object-id` tries (and succeeds) to base64-decode the issue ID, even though it's not encoded, and that seems to result in the problem in this case.

But is that function actually ever called with those arguments?  I don't think it is, the `ID` argument is (except in one special case) always an integer.

Also, why do you think this is related to the issue at hand. (Regardless, it is useful that you brought this up because:)

> I don't really understand why it's doing the decoding though.

I think that's old code that I failed to adjust when I made other changes.  When `ID` is an integer, as it nearly always is, then trying to decode it will fail and `ID` will be used as-is, which is what is intended.

The one case where `ID` is a string concerns a case where we are forced to use the "name" of an object instead of its id due to what I consider a bug in the Gitlab API.

<details>

``` emacs-lisp
(cl-defmethod forge--update-labels ((repo forge-gitlab-repository) data)
  (oset repo labels
        (with-slots (id) repo
          (mapcar (lambda (row)
                    (let-alist row
                      ;; We should use the label's `id' instead of its
                      ;; `name' but a topic's `labels' field is a list
                      ;; of names instead of a list of ids or an alist.
                      ;; If a label is renamed, then things break.
                      (list (forge--object-id id .name)
                            .name
                            (downcase .color)
                            .description)))
                  data))))
```

</details>

But in that case too we don't actually want to decode the string, because it is something like "bug" or "enhancement".  So I think I will just drop the `base64-decode-string` here.  In the future we might encounter strings that should be decoded again, but if and when that happens then we probably should add a new method for that special case.

**Comment by tarsius** [comment]
> So I think I will just drop the `base64-decode-string` here.

Unfortunately we cannot do that because it would break the database.  So I am delaying that change until there is another more important reason to do that anyway (and force users to reset the database).

In any case, it would not matter for the issue at hand because it only Gitlab, while this issue is about Github.

**Comment by flodiebold** [comment]
> But is that function actually ever called with those arguments? I don't think it is, the `ID` argument is (except in one special case) always an integer.
> 
> Also, why do you think this is related to the issue at hand? (Regardless, it is useful that you brought this up because:)

It is called with those arguments when I do `forge-pull-notifications` for github, and ultimately causes the `Parse error on \"+\"` error for me... that's also why I think this is related to the issue ;)

Adding
```elisp
(when (string-match-p "\\+" id)
        (message "> %s/%s#%s %S %S %S .id: %S stringp .id: %S"
                 owner name number
                 repoid id key .id (stringp .id)))
```
in the place you suggested gives
```
> rust-lang/rfcs#1250 "Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTE3NTI3OTg5" "Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTE3NTI3OTg5OvePO9+NPQ==" _Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTE3NTI3OTg5OvePO9+NPQ__ .id: "94873409" stringp .id: t
> rust-lang/rfcs#1203 "Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTE3NTI3OTg5" "Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTE3NTI3OTg5OvPfN+eN9A==" _Z2l0aHViLmNvbTowMTA6UmVwb3NpdG9yeTE3NTI3OTg5OvPfN+eN9A__ .id: "89835430" stringp .id: t
```
for me.

**Comment by tarsius** [comment]
Could you please insert  `(when (stringp id) (error "gimme backtrace"))` so that I can see how that functions ends up being called like that. I looked at the code and didn't find anything that called it like that and I also added debug statements and that also didn't show it being called like that. It appears I did something wrong when doing those things, so a backtrace would help.

**Comment by flodiebold** [comment]
The stacktrace is huge and probably contains private data, so I'm not going to paste all of it, but here's part of it:
```
forge--ghub-massage-notification(((id . "428973754") (unread . t) (reason . "subscribed") (updated_at . "2018-12-29T15:20:19Z") (last_read_at . "2018-12-29T09:20:25Z") (subject (title . "Display inline images in topics") (url . "https://api.github.com/repos/magit/forge/pulls/47") (latest_comment_url . "https://api.github.com/repos/magit/forge/issues/comments/450499726") (type . "PullRequest")) (repository (id . 141378194) (node_id . "MDEwOlJlcG9zaXRvcnkxNDEzNzgxOTQ=") (name . "forge") (full_name . "magit/forge") (private) (owner (login . "magit") (id . 750076) (node_id . "MDEyOk9yZ2FuaXphdGlvbjc1MDA3Ng==") ....
(closure ((apihost . "api.github.com") (forge . "github.com") (x416) (x414 forge-github-repository) (x413 . "github.com") (x412 "github.com" forge-github-repository) (x411 . "api.github.com") (x410 "api.github.com" "github.com" forge-github-repository) (spec "github.com" "api.github.com" "github.com" forge-github-repository) (callback) (githost . "github.com") (_class . forge-github-repository ....
mapcar((closure ((apihost . "api.github.com") (forge . "github.com") ....
(let* ((notifs (mapcar (function (lambda (it) (forge--ghub-massage-notification it ....
(let ((forge x413) (apihost x411)) (let* ((notifs ....
(let* ((x410 (cdr spec)) ....
(let ((spec (assoc githost forge-alist))) (if spec nil ....
(progn (let ....
(closure (t) (_class githost &optional callback) (progn (let ....
apply((closure (t) (_class githost &optional callback) (progn (let ....
forge--pull-notifications(forge-github-repository "github.com")
forge-pull-notifications()
funcall-interactively(forge-pull-notifications)
call-interactively(forge-pull-notifications)
magit-invoke-popup-action(89)
funcall-interactively(magit-invoke-popup-action 89)
call-interactively(magit-invoke-popup-action nil nil)
command-execute(magit-invoke-popup-action)
````

At least for me, all the ids for the notifications themselves seem to be strings, as returned by `forge--ghub-get`:
```
ELISP> (forge--ghub-get nil "/notifications"
                                         '((all . "true"))
                                         :host "api.github.com" :unpaginate t)
(((id . "428973754")
  (unread . t)
  (reason . "subscribed")
  (updated_at . "2018-12-29T15:20:19Z")
  (last_read_at . "2018-12-29T09:20:25Z")
  (subject
   (title . "Display inline images in topics")
   (url . "https://api.github.com/repos/magit/forge/pulls/47")
   (latest_comment_url . "https://api.github.com/repos/magit/forge/issues/comments/450499726")
   (type . "PullRequest"))
  (repository
   (id . 141378194)
   (node_id . "MDEwOlJlcG9zaXRvcnkxNDEzNzgxOTQ=")
   (name . "forge")
   (full_name . "magit/forge")
....
```

**Comment by tarsius** [comment]
Ah, I overlooked that one.  (The GraphQL API returns integers, but here we use the REST API.)

Please check whether 6586fcca074d4d0da57b22fca4bb9e97938462ac fixes this issue.
